### ISSUE TITLE
headObject 没有返回自定义 Header

### ISSUE THREAD

**Issue by cncolder** [tencentyun/cos-js-sdk-v5#10]
目前返回的 headers 只包含 `cache-control` `content-type` `stag` `last-modified`.
其他的诸如 `Content-Disposition` 或 `x-cos-meta-*` 都没在返回值里.

**Comment by carsonxu** [comment]
这个需要你在 CORS 里面配置这几个字段允许 js 获取：
ExposeHeaders:
Content-Disposition
x-cos-meta-a
x-cos-meta-b
x-cos-meta-c

**Comment by cncolder** [comment]
原来如此, 要是 Expose Headers 支持通配符就好了 `x-cos-meta-*`

**Comment by carsonxu** [comment]
不支持的~
