### ISSUE TITLE
uniapp小程序引入报错，不知道咋解决。。。

### ISSUE THREAD

**Issue by xiaoqingb** [tencentyun/cos-js-sdk-v5#100]
`import Vue from 'vue';
import App from './App';
import store from './store';
import cos from 'cos-js-sdk-v5';
console.log(cos);
Vue.config.productionTip = false;
Vue.prototype.$store = store;
App.mpType = 'app';

const app = new Vue({
    ...App
});
app.$mount();
`js
`
VM1016:5 app.js错误:
 TypeError: Cannot read property 'match' of undefined
    at check (null:367)
    at null:374
    at Object.<anonymous> (null:376)
    at __webpack_require__ (null:91)
    at Object.<anonymous> (null:66)
    at __webpack_require__ (null:91)
    at Object.<anonymous> (null:52)
    at __webpack_require__ (null:91)
    at Object.<anonymous> (main.js? [sm]:4)
    at Object.0 (VM995 main.js:25)
`

**Comment by xiaoqingb** [comment]
<img width="1128" alt="截屏2021-03-01 上午1 01 44" src="https://user-images.githubusercontent.com/49091613/109426653-af67df00-7a29-11eb-859f-6d1fbd20e4cd.png">

**Comment by xiaoqingb** [comment]
![Uploading 截屏2021-03-01 上午1.02.59.png…]()

**Comment by xiaoqingb** [comment]
<img width="1128" alt="截屏2021-03-01 上午1 02 59" src="https://user-images.githubusercontent.com/49091613/109426747-256c4600-7a2a-11eb-8bae-07fd8ef5b442.png">

**Comment by carsonxu** [comment]
SDK 本身比支持 uniapp，需要在不同场景用不同 SDK。
这个问题是什么原因导致报错？怎么解决？
