### ISSUE TITLE
新项目安装了1.2.6版本的依赖，结果代码报错

### ISSUE THREAD

**Issue by indingpig** [tencentyun/cos-js-sdk-v5#101]
提示如下：
Uncaught (in promise) TypeError: Cannot read property 'XCosSecurityToken' of undefined

1.1.10版本，并没有这个问题

**Comment by carsonxu** [comment]
如何调用？

**Comment by indingpig** [comment]
data 是从后台获取的。公司里几个项目都是这么获取的。
从接口和代码中查看，data是有值的
`let obj = {
        TmpSecretId: data.credentials.tmpSecretId,
        TmpSecretKey: data.credentials.tmpSecretKey,
        XCosSecurityToken: data.credentials.sessionToken,
        ExpiredTime: data.credentials.expiredTime
      };
      let cos = new COS({
        getAuthorization: function (options, callback) {
          callback(obj);
        }
      });`

**Comment by carsonxu** [comment]
这个抛错误已处理，更新 cos-js-sdk-v5@1.2.7，看看你签名是有什么格式问题？

**Comment by indingpig** [comment]
已解决

**Comment by indingpig** [comment]
多谢开发者
