### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Hxmic** [tencentyun/cos-js-sdk-v5#102]
有没有pc 端，简单上传的demo

**Comment by carsonxu** [comment]
https://cloud.tencent.com/document/product/436/9067

**Comment by Hxmic** [comment]
好的，感谢

**Comment by Hxmic** [comment]
ts 中 会有这个问题。 用 d.ts 声明没有解决。 改成 js 了
![image](https://user-images.githubusercontent.com/23522154/111587554-55bf2d00-87fd-11eb-86bc-55ba7f69100e.png)

**Comment by carsonxu** [comment]
@Hxmic 看不出来问题位置，给一下上下文？

**Comment by Hxmic** [comment]
最近配置上域名，然后上传还是有点问题。 有空麻烦指导一下。



![image](https://user-images.githubusercontent.com/23522154/122916911-00606200-d390-11eb-9911-93a645878927.png)


![image](https://user-images.githubusercontent.com/23522154/122916958-0e15e780-d390-11eb-9343-5ac55de1761a.png)

**Comment by livehigh** [comment]
> 最近配置上域名，然后上传还是有点问题。 有空麻烦指导一下。
> 
> ![image](https://user-images.githubusercontent.com/23522154/122916911-00606200-d390-11eb-9911-93a645878927.png)
> 
> ![image](https://user-images.githubusercontent.com/23522154/122916958-0e15e780-d390-11eb-9343-5ac55de1761a.png)
> 
> @carsonxu 大佬帮忙看看白。

有没有配置跨域
![image](https://user-images.githubusercontent.com/25949099/123912083-2baa0900-d9af-11eb-92dd-3a9fe9df9103.png)

**Comment by qq992064577** [comment]
let that = this;
    await requestCloudWechat("/tencentCloud/cosCredential/getCredential.do", {
      region: requestCos.region,
      bucket: requestCos.bucket,
    }).then((res) => {
      if (res.resultCode === 0) {
        this.record = res.data.record;
        this.cos = new COS({
        getAuthorization:(options, callback) =>{
              callback({
                  TmpSecretId: that.record.credentials.tmpSecretId,
                  TmpSecretKey: that.record.credentials.tmpSecretKey,
                  SecurityToken: that.record.credentials.sessionToken,
     // 建议返回服务器时间作为签名的开始时间，避免用户浏览器本地时间偏差过导致签名错误
                  StartTime: that.record.startTime, // 时间戳，单位秒，如：1580000000
                  ExpiredTime: that.record.expiredTime, // 时间戳，单位秒，如：  1580000900
              }); 
        },
      });
      }
    });

//为什么可以帮我看看签名为什么不能成功吗
![微信截图_20210713173646](https://user-images.githubusercontent.com/70893645/125429342-f72e3a96-0358-4416-a10b-0022627fabb1.png)

**Comment by livehigh** [comment]
> let that = this; await requestCloudWechat("/tencentCloud/cosCredential/getCredential.do", { region: requestCos.region, bucket: requestCos.bucket, }).then((res) => { if (res.resultCode === 0) { this.record = res.data.record; this.cos = new COS({ getAuthorization:(options, callback) =>{ callback({ TmpSecretId: that.record.credentials.tmpSecretId, TmpSecretKey: that.record.credentials.tmpSecretKey, SecurityToken: that.record.credentials.sessionToken, // 建议返回服务器时间作为签名的开始时间，避免用户浏览器本地时间偏差过导致签名错误 StartTime: that.record.startTime, // 时间戳，单位秒，如：1580000000 ExpiredTime: that.record.expiredTime, // 时间戳，单位秒，如： 1580000900 }); }, }); } });
> 
> //为什么可以帮我看看签名为什么不能成功吗 ![微信截图_20210713173646](https://user-images.githubusercontent.com/70893645/125429342-f72e3a96-0358-4416-a10b-0022627fabb1.png)

是后端getCredential服务没通还是和前端联调不成功呢。
需要详细信息

**Comment by qq992064577** [comment]
这边服务器联通了，就是实例化cos的时候返回失败
![image](https://user-images.githubusercontent.com/70893645/146631585-46df8cd1-1d16-4649-bb27-b5adfbbb79de.png)
