### ISSUE TITLE
有没有同步调用STS.getCredential的方法？

### ISSUE THREAD

**Issue by tingshuai** [tencentyun/cos-js-sdk-v5#103]
我使用的是nestjs 基本都是await 同步返回模式，有没有同步调用的方法

**Comment by carsonxu** [comment]
已优化支持。
qcloud-cos-sts@3.0.3

**Comment by tingshuai** [comment]
> 已优化支持。
> qcloud-cos-sts@3.0.3
文档，相关链接发个呀

**Comment by carsonxu** [comment]
文档：
https://cloud.tencent.com/document/product/436/14048
https://github.com/tencentyun/qcloud-cos-sts-sdk/tree/master/nodejs
示例：
https://github.com/tencentyun/qcloud-cos-sts-sdk/blob/master/nodejs/demo/demo.js
```
const async fn = () => {
  const credential = await STS.getCredential({
      secretId: ''
      secretKey: '',
      policy: policy,
      durationSeconds: 7200,
  });
  console.log(credential);
}
```

**Comment by tingshuai** [comment]
谢谢
