### ISSUE TITLE
你好，请教一个问题

### ISSUE THREAD

**Issue by youbooks** [tencentyun/cos-js-sdk-v5#11]
你好，我现在遇到一个上传多张图片的问题，微信小程序  本地相册选择了8张图片， 应该调用哪个api 才能上传到腾讯云cos 中 ？？？

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cos-wx-sdk-v5
使用这个 SDK，有个 cos.postObject 方法，一个个传给他就好
