### ISSUE TITLE
下载的返回数据data.Body是string类型。转blob时文件损坏。请问应该如何实现浏览器下载？

### ISSUE THREAD

**Issue by jinan5694** [tencentyun/cos-js-sdk-v5#117]
![image](https://user-images.githubusercontent.com/3690120/124530170-9390a180-de3e-11eb-8a81-0c1fc19d9ca3.png)

我想通过数据流的方式转换，这样可以对下载的文件重命名。

**Comment by carsonxu** [comment]
浏览器下载文件，是获取一个 url，交给带 download 属性的 a 标签下载，参考这个示例五
https://cloud.tencent.com/document/product/436/35651#.E4.B8.8B.E8.BD.BD.E8.AF.B7.E6.B1.82.E7.A4.BA.E4.BE.8B

如果是要用 cos.getObject 也可以，传入参数 DataType: 'blob'
