### ISSUE TITLE
上传成功回调支持万象优图的location

### ISSUE THREAD

**Issue by szhjia** [tencentyun/cos-js-sdk-v5#12]
您好，可否在上传成功后增加万象优图的location，多谢。

**Comment by carsonxu** [comment]
试试“无服务器云函数”

**Comment by carsonxu** [comment]
这里暂不添加，COS 的 SDK 如果添加了优图 Location 反而会有疑问。
可以自行凭借或者通过 getObjectUrl 获取之后替换字符串。
