### ISSUE TITLE
这api到底是哪个大聪明设计的，能不能学学阿里、七牛

### ISSUE THREAD

**Issue by uoau** [tencentyun/cos-js-sdk-v5#122]

**Comment by carsonxu** [comment]
你希望的 API 是怎么样？

**Comment by uoau** [comment]
1、STS返回TmpSecretId、TmpSecretKey、XCosSecurityToken完全不知道什么场景下使用，为什么要分开，合成一个token不行吗。
![image](https://user-images.githubusercontent.com/41247996/129451221-c03fe669-234d-4e87-9dfc-803a8929f4b2.png)
解释得好像没解释一样，谁知道这些是干啥的

2、腾讯SDK文档里，教程和文档写在一起，想到啥写啥，毫无逻辑可言。如果是api文档，能不能根据对象\角色分开，然后每个对象\角色下列举各自的API，参考小程序文档、node文档、谷歌开发者文档。
![image](https://user-images.githubusercontent.com/41247996/129451199-1631b325-bd95-4db2-9f21-973de8118f93.png)

要是让我设计腾讯云js上传文档，我会这样设计目录
```
Init 初始化
    - new Cos
Bucket 存储桶
    - headBucket 鉴权
    - deleteBucket 删除
    - ...
Object 对象
    - putObject 简单上传
    - getBucket 查询列表
    - ....
```
