### ISSUE TITLE
发现一个小错误，期待TS文件更新

### ISSUE THREAD

**Issue by king-peach** [tencentyun/cos-js-sdk-v5#123]
调用方式是这样的
```javascript
//  处理文件完成
    var _onFileFinish = params.onFileFinish;
    var onFileFinish = function (err, data) {
       // onFileFinish方法参数TS类型定义错误
        _onFileFinish && _onFileFinish(err, data, fileInfo);
        callback && callback(err, data);
    };
```
但是TS类型却是这样定义的
```typescript
// uploadFile 高级上传
  interface FileFinishInfo {
    err: Error;
    data: UploadFileItemResult;
    options: UploadFileItemParams;
  }
  type onFileFinish = (params: FileFinishInfo) => void;
```
麻烦处理下这块，或者给一个好的解决方法，谢谢🙏

**Comment by livehigh** [comment]
> 调用方式是这样的
> 
> ```js
> //  处理文件完成
>     var _onFileFinish = params.onFileFinish;
>     var onFileFinish = function (err, data) {
>        // onFileFinish方法参数TS类型定义错误
>         _onFileFinish && _onFileFinish(err, data, fileInfo);
>         callback && callback(err, data);
>     };
> ```
> 
> 但是TS类型却是这样定义的
> 
> ```ts
> // uploadFile 高级上传
>   interface FileFinishInfo {
>     err: Error;
>     data: UploadFileItemResult;
>     options: UploadFileItemParams;
>   }
>   type onFileFinish = (params: FileFinishInfo) => void;
> ```
> 
> 麻烦处理下这块，或者给一个好的解决方法，谢谢🙏

v1.3.0已修复，感谢反馈
