### ISSUE TITLE
uploadFile

### ISSUE THREAD

**Issue by RoadAspen** [tencentyun/cos-js-sdk-v5#125]
使用 uploadFile 上传分块组件，当调用cancelTask（taskId） 的之后，重新上传文件时，会从0开始上传，那么之前的文件碎片怎么删除呢？
目测 cancelTask 并不能删除文件碎片， multipartAbort 却需要 uploadId

**Comment by carsonxu** [comment]
cos.cancelTask 只会删除 SDK 的任务，不会清理 UploadId
清理 UploadId，可以这样：
1. 方案1：不在取消的时候清理，而是 COS 控制台设置生命周期，定期清理碎片
2. 方案2：可以调用 cos.abortUploadTask({ ...opt, Key: 'xxx.jpg', Level: 'file' }) 清理该文件的所有碎片
