### ISSUE TITLE
Pic-Operations 中文文件名 如何传递

### ISSUE THREAD

**Issue by hjkltop** [tencentyun/cos-js-sdk-v5#126]
'Pic-Operations':
            JSON.stringify({
                "is_pic_info": 1,
                "rules": [{
                    "fileid": camSafeUrlEncode(key), "rule": transformWatermarkQuery(config)
                }]
            })

使用 encodeURIComponent 传递，没报错，但是带中文的水印传不上去。
尝试了camSafeUrlEncode  400 Bad Request

**Comment by livehigh** [comment]
> ```
>     'Pic-Operations':
>         JSON.stringify({
>             "is_pic_info": 1,
>             "rules": [{
>                 "fileid": camSafeUrlEncode(key), "rule": transformWatermarkQuery(config)
>             }]
>         })
> ```
> 
> 使用 encodeURIComponent 传递，没报错，但是带中文的水印传不上去。 尝试了camSafeUrlEncode 400 Bad Request

抱歉这里暂时不支持fileid为中文，团队内部已经在做方案评估
