### ISSUE TITLE
Type declaration issue

### ISSUE THREAD

**Issue by Shsgear** [tencentyun/cos-js-sdk-v5#132]
![image](https://user-images.githubusercontent.com/20643994/143521080-d202d3a4-57c2-47c0-91e1-d0a577661ea4.png)

version: 1.3.1

tsc output errors during compile time.
`All declarations of 'Action' must have identical modifiers.`

Probably with the name conflict when two interfaces are merging  #131 

https://github.com/tencentyun/cos-js-sdk-v5/commit/9737bacbf778a63463f94fd7f8da4c371fa63e69#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R1862

https://github.com/tencentyun/cos-js-sdk-v5/commit/9737bacbf778a63463f94fd7f8da4c371fa63e69#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R1828

**Comment by livehigh** [comment]
fixed in v1.3.2
