### ISSUE TITLE
前端向服务端获取签名，请求了4次

### ISSUE THREAD

**Issue by yangguansen** [tencentyun/cos-js-sdk-v5#134]
我按照文档，向node端获取签名，本地开发环境，会请求1次，但是放到服务器上，请求了4次，请问有遇到过相关情况吗？

这是请求了4次的情况：
![image](https://user-images.githubusercontent.com/24775952/145012559-13f59907-a063-4dba-a587-8b74cacd905d.png)

这是请求了1次的情况：
![image](https://user-images.githubusercontent.com/24775952/145012682-402b58d4-0284-4a1a-969d-8203fae327bd.png)

**Comment by livehigh** [comment]
需确认代码
