### ISSUE TITLE
bug: 异步的case 做了万象的兼容，同步的没有处理导致签名不一致拿不到图片，已经亲自验证过了

### ISSUE THREAD

**Issue by a931528933** [tencentyun/cos-js-sdk-v5#139]
https://github.com/tencentyun/cos-js-sdk-v5/blob/c2e7a91163e504e1bf03aa4840c793628c83a175/dist/cos-js-sdk-v5.js#L7913

**Comment by livehigh** [comment]
> 我是调用同步的api

辛苦先使用异步的方式。
您这边有什么场景必须使用同步的方式？
