### ISSUE TITLE
getAuthorization 频繁请求，如何设置失败回调次数？

### ISSUE THREAD

**Issue by xuxchao** [tencentyun/cos-js-sdk-v5#142]
最近遇到了后端服务挂掉的情况，导致用户上传图片的时候获取权限失败。然后 getAuthorization 方法一直被调用。请问又办法控制失败重新请求次数么？

我看 ts 类型描述是没有相关参数的，请问这个有计划补充么？要是有能给个时间就最棒了

**Comment by mrxu0** [comment]
![image](https://user-images.githubusercontent.com/28293069/155647844-d309ff44-cd7d-46f6-8d4a-afd46a66d799.png)

**Comment by livehigh** [comment]
> 

正常情况不会这样重试的，辛苦贴一下代码我们定位一下。（注意屏蔽下敏感信息）

**Comment by Mr-Geneo** [comment]
@xuxchao 你是不是也开启了ScopeLimit
