### ISSUE TITLE
请问使用 getObject 下载视频文件不支持吗，datatype属性不生效呢

### ISSUE THREAD

**Issue by brahmachen** [tencentyun/cos-js-sdk-v5#144]
https://cloud.tencent.com/document/product/436/64961
根据文档，可以使用cos.getObject 下载对象，同时可以定义dataType 为blob 或者arraybuffer，但是我使用时不太正常，看起来像是下载文件内容发生了损坏，请问是哪个地方不对呢？

**Comment by brahmachen** [comment]
```js
    this.cosInstance.getObject({
      Bucket: this.bucket, /* 必须 */
      Region: this.region, /* 存储桶所在地域，必须字段 */
      Key: url, /* 必须 */
      DataType: 'blob',
    }, (err, data) => {
      // console.log(err || data);
      if (data) {
        resolve(this.str2ab(data.Body));
      } else {
        reject(err);
      }
    });
```
具体现象是，下载时控制台出现大量的报错信息，下载时间大大超出了视频文件大小的时间，并且data.Body仍然是个字符串
![image](https://user-images.githubusercontent.com/12797533/158932531-fe11c246-d651-4a50-84f3-d9e2424de4b9.png)

**Comment by livehigh** [comment]
sdk版本多少？data.Body仍然是个字符串可能是DataType: 'blob'参数没有生效
