### ISSUE TITLE
update  cos-js-sdk-v5  打包报错

### ISSUE THREAD

**Issue by 1159733927** [tencentyun/cos-js-sdk-v5#157]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/53029571/185092577-00932bf0-d82c-445a-ad92-0ce4c84ef1a1.png">

**Comment by livehigh** [comment]
辛苦先把版本锁定在1.3.10，今天会发布个新版本修复

**Comment by livehigh** [comment]
1.4.1版本已修复
