### ISSUE TITLE
cos-js-sdk-v5  打包出错了

### ISSUE THREAD

**Issue by hejialianghe** [tencentyun/cos-js-sdk-v5#158]
error  in ./node_modules/vod-js-sdk-v6/node_modules/cos-js-sdk-v5/src/tracker.js
Module parse failed: Unexpected token (34:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       if (typeof navigator === 'object') {
|         const connection = navigator.connection || navigator.mozConnection || navigator.webkitConnection;
>         return connection?.type || connection?.effectiveType || 'unknown';
|       }
|       return 'unknown';

@ ./node_modules/vod-js-sdk-v6/node_modules/cos-js-sdk-v5/src/util.js 7:14-34
@ ./node_modules/vod-js-sdk-v6/node_modules/cos-js-sdk-v5/src/cos.js
@ ./node_modules/vod-js-sdk-v6/lib/src/uploader.js
@ ./node_modules/@myfe/vod-js-sdk/lib/index.js
@ ./node_modules/@maoyanhk/seat-designer/lib/core/seat-designer.js
@ ./src/components/seat_plan_client/index.tsx
@ ./src/pages/customer/tickets_operating/change_tickets/seat_plan/index.tsx
@ ./src/.umi-production/core/routes.ts
@ ./src/.umi-production/umi.ts

1. 在webpack 加入可混淆压缩，你们没兼容？语法哇

**Comment by hejialianghe** [comment]
![image](https://user-images.githubusercontent.com/32085679/185095153-d89961ca-90f7-4425-8880-200144b68422.png)
#

**Comment by xbw187** [comment]
一样 楼主你解决了吗

**Comment by thankslyh** [comment]
目前我这边是降级处理的，我降级到1.1.0

**Comment by hejialianghe** [comment]
降级吧

**Comment by livehigh** [comment]
辛苦先把版本锁定在1.3.10，今天会发布个新版本修复

**Comment by livehigh** [comment]
1.4.1版本已修复
