### ISSUE TITLE
@xmldom/xmldom 包更新

### ISSUE THREAD

**Issue by NPjuan** [tencentyun/cos-js-sdk-v5#163]
@xmldom/xmldom 0.8.3之前版本存在安全漏洞，详情如下
https://vul.wangan.com/a/CNNVD-202210-498

麻烦升级一下该依赖包

**Comment by livehigh** [comment]
感谢反馈，计划今天发布一个版本来做升级




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tencentyun/cos-js-sdk-v5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 上午10:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tencentyun/cos-js-sdk-v5] @xmldom/xmldom 包更新 (Issue #163)





 
@xmldom/xmldom 0.8.3之前版本存在安全漏洞，详情如下
 https://vul.wangan.com/a/CNNVD-202210-498
 
麻烦升级一下该依赖包

**Comment by livehigh** [comment]
fixed in v1.4.11
