### ISSUE TITLE
CI 调用审核的文本接口提示无权限

### ISSUE THREAD

**Issue by nasawz** [tencentyun/cos-js-sdk-v5#174]
[request id:NjNkYmI2YjdfZDVjZTlmMGJfM2M0Yl8yMGNjNQ==AuthAndSign]you are not authorized to perform operation (ci:CreateAuditingTextJob)
resource (qcs::ci:xxxxx:uid/xxxx:bucket/xxxxx-125633312109/job/*) has no permission

**Comment by livehigh** [comment]
使用临时密钥需要给与相应操作的权限哈
