### ISSUE TITLE
使用 vite 打包时 出现警告

### ISSUE THREAD

**Issue by Ganlvin** [tencentyun/cos-js-sdk-v5#176]
Use of eval in "node_modules/cos-js-sdk-v5/dist/cos-js-sdk-v5.js" is strongly discouraged as it poses security risks and may cause issues with minification.

 "vite": "^4.1.1",
 "cos-js-sdk-v5": "^1.4.15",

**Comment by livehigh** [comment]
fixed in v1.5.0
