### ISSUE TITLE
使用 Nodejs 引入包后出现 ReferenceError: self is not defined

### ISSUE THREAD

**Issue by Logosww** [tencentyun/cos-js-sdk-v5#178]
研究了一下，原因是 `webpack.config.js` 中的 output.globalObject 配置项为 `self`，能不能改成 `this`？
至于为什么使用了 Nodejs 引入包，是因为项目是 SSR 的，使用 Nuxt 3 框架，在引入模块的时候用的 Nodejs 新的 ESM 检测引入机制，机制没问题，事实上单独引入这个包的时候确实是以 CJS 引入的，但是 Nuxt 3 最后是把代码打包成 ESM 在 Nodejs 上运行的，这样就出现了问题。
![image](https://user-images.githubusercontent.com/87473526/222113450-01e4f7db-14a6-42c3-b5de-c8770a2d6586.png)

**Comment by livehigh** [comment]
> 

感谢你的反馈，我们使用self兼容了web和web worker，准备改成this以兼容ssr的场景

**Comment by livehigh** [comment]
fixed in v1.4.16
