### ISSUE TITLE
如何读取私读权限的文件

### ISSUE THREAD

**Issue by dodoto** [tencentyun/cos-js-sdk-v5#181]
使用 getObjectUrl 进行文件读取, 一直返回403.已经确保 key 正确无误.

**Comment by livehigh** [comment]
可以先这样排查下：
若使用临时密钥生成预签名 URL，请确保申请临时密钥的 action 添加了 "name/cos:GetObject" 权限。以及申请临时密钥时授权的路径覆盖了Key。比如申请临时密钥时填写的allowPrefix为“a/b/*”,那么Key必须以“a/b/”开头。

如果还是有问题的话可以提供403的requestId帮你查一下

> 使用 getObjectUrl 进行文件读取, 一直返回403.已经确保 key 正确无误.

**Comment by dodoto** [comment]
name/cos:GetObject 配置成了 name/cos:GetObjectUrl 了
