### ISSUE TITLE
这行里有个打错的注释

### ISSUE THREAD

**Issue by nmsn** [tencentyun/cos-js-sdk-v5#184]
https://github1s.com/tencentyun/cos-js-sdk-v5/blob/HEAD/src/base.js#L2719

![image](https://user-images.githubusercontent.com/23231239/236104342-25fdd7dd-768a-4bd3-a008-d2825a4ccd1d.png)

是追加到 10000 片么

**Comment by livehigh** [comment]
感谢反馈，这里应该是“最多”
