### ISSUE TITLE
1.4.15升级到1.4.17运行报错，降级到1.4.16后正常

### ISSUE THREAD

**Issue by zhongzhifa** [tencentyun/cos-js-sdk-v5#186]
![image](https://user-images.githubusercontent.com/25548250/236361284-493184ab-f32f-4311-bd43-cb997f14d000.png)

**Comment by livehigh** [comment]
> ![image](https://user-images.githubusercontent.com/25548250/236361284-493184ab-f32f-4311-bd43-cb997f14d000.png)

有尝试卸载后重装吗
