### ISSUE TITLE
cos-js-sdk-v5.js:1834 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript

### ISSUE THREAD

**Issue by allahbinplus** [tencentyun/cos-js-sdk-v5#193]
<img width="585" alt="image" src="https://github.com/tencentyun/cos-js-sdk-v5/assets/111942056/a4e4982a-57c3-4db7-804e-425ef4ceca1e">

错误在这里
<img width="319" alt="image" src="https://github.com/tencentyun/cos-js-sdk-v5/assets/111942056/2170a377-1c3a-4b26-83bd-3191024e1671">

**Comment by livehigh** [comment]
辛苦提供下使用版本，使用环境，使用框架等信息
