### ISSUE TITLE
putObject上传的文件，在控制台点击文件链接下载下来，却无法预览，不知是什么问题，请教。

### ISSUE THREAD

**Issue by yue00xl** [tencentyun/cos-js-sdk-v5#2]
var File = document.getElementById('file');
File.onchange=function(){
    for(var i=0; i<this.files.length;i++){
        putObject(this.files[i].size,'pic/'+this.files[i].name,util.createFile(this.files[i]));
    }
}

function putObject(key,blob) {
    // 调用方法
    cos.putObject({
        Bucket: config.Bucket, /* 必须 */
        Region: config.Region,
        Key:key, /* 必须 */
        Body: blob,
        TaskReady: function (tid) {
            TaskId = tid;
        },
        onProgress: function (progressData) {
             console.log('普通上传');
            console.log(JSON.stringify(progressData.percent));
        },
    }, function (err, data) {
        console.log(err || data);
    });
}

**Comment by carsonxu** [comment]
function putObject(key,blob) {
这个参数定义错了吧？？是不是应该改成
function putObject(size, key, blob)
