### ISSUE TITLE
调用uploadFile，为什么返回了BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it

### ISSUE THREAD

**Issue by thousandsNight** [tencentyun/cos-js-sdk-v5#201]
调用uploadFile会新建bucket？

**Comment by livehigh** [comment]
辛苦确认参数 Key 是否填写正确

**Comment by thousandsNight** [comment]
![image](https://github.com/tencentyun/cos-js-sdk-v5/assets/11659929/3d92fd45-33c9-4824-8f75-bd7101f98bca)
![image](https://github.com/tencentyun/cos-js-sdk-v5/assets/11659929/6c8172f5-d642-4e70-a8b2-aeb2aec8f435)
麻烦看下哪里不对

**Comment by livehigh** [comment]
> ![image](https://private-user-images.githubusercontent.com/11659929/294437696-3d92fd45-33c9-4824-8f75-bd7101f98bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDQwOTAsIm5iZiI6MTcwNDQ0Mzc5MCwicGF0aCI6Ii8xMTY1OTkyOS8yOTQ0Mzc2OTYtM2Q5MmZkNDUtMzNjOS00ODI0LThmNzUtYmQ3MTAxZjk4YmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNGM5Njk4YzljZWE0MzBjM2IxNjA2MTZiYjkyOGMwMTdlMTgxMDU3MTJiMzM0YTA0MmNhOTg2NzE4ZWU5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSqbF-y7E-P0EIezdm4UZ0zz74X9qnKNw-vuIiteec4) ![image](https://private-user-images.githubusercontent.com/11659929/294437987-6c8172f5-d642-4e70-a8b2-aeb2aec8f435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDQwOTAsIm5iZiI6MTcwNDQ0Mzc5MCwicGF0aCI6Ii8xMTY1OTkyOS8yOTQ0Mzc5ODctNmM4MTcyZjUtZDY0Mi00ZTcwLWE4YjItYWViMmFlYzhmNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNDYwNzY2NzYwYTZkODA1ZDc5YTFhOGEzOThmNDZkNDMxMTZmYjYwM2E0MmEwMTNkMDdmZDE3OTAwZDlhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4pGAw9M-BpTgZFKJOlGyNuFOBjatUkV5uxpWYXgZU8) 麻烦看下哪里不对

Key首字母大写

**Comment by thousandsNight** [comment]
> > ![image](https://private-user-images.githubusercontent.com/11659929/294437696-3d92fd45-33c9-4824-8f75-bd7101f98bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDQwOTAsIm5iZiI6MTcwNDQ0Mzc5MCwicGF0aCI6Ii8xMTY1OTkyOS8yOTQ0Mzc2OTYtM2Q5MmZkNDUtMzNjOS00ODI0LThmNzUtYmQ3MTAxZjk4YmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNGM5Njk4YzljZWE0MzBjM2IxNjA2MTZiYjkyOGMwMTdlMTgxMDU3MTJiMzM0YTA0MmNhOTg2NzE4ZWU5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSqbF-y7E-P0EIezdm4UZ0zz74X9qnKNw-vuIiteec4) ![image](https://private-user-images.githubusercontent.com/11659929/294437987-6c8172f5-d642-4e70-a8b2-aeb2aec8f435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDQwOTAsIm5iZiI6MTcwNDQ0Mzc5MCwicGF0aCI6Ii8xMTY1OTkyOS8yOTQ0Mzc5ODctNmM4MTcyZjUtZDY0Mi00ZTcwLWE4YjItYWViMmFlYzhmNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNDYwNzY2NzYwYTZkODA1ZDc5YTFhOGEzOThmNDZkNDMxMTZmYjYwM2E0MmEwMTNkMDdmZDE3OTAwZDlhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4pGAw9M-BpTgZFKJOlGyNuFOBjatUkV5uxpWYXgZU8) 麻烦看下哪里不对
> 
> Key首字母大写

成功了，感谢

**Comment by livehigh** [comment]
ok
