### ISSUE TITLE
支持大文件上传吗

### ISSUE THREAD

**Issue by slince** [tencentyun/cos-js-sdk-v5#21]
会不会自动检查文件大小，采用自动分片的方式上传

**Comment by carsonxu** [comment]
sliceUploadFile 接口不会自动检查，你可以自行检查大小分别调用 sliceUpload、putObject 两个接口

**Comment by slince** [comment]
谢谢。有和 plupload，WebUploader 这样的前端上传库结合的计划吗；

**Comment by slince** [comment]
@carsonxu  忘了@

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cos-plupload
https://github.com/annexwu/cos-webuploader
这里有两个，但都只是用了选文件的动作，结合的不够深入

**Comment by slince** [comment]
其实本sdk可以废弃；只要用plupload来做前端解决方案就好，plupload自带的有切片以及压缩方案，而且和ui结合也更方便； @carsonxu

**Comment by carsonxu** [comment]
谢谢建议，但如果是我会直接使用 SDK，webuploader 和 plupload 都是较大型的库。只引用 SDK 更简洁
