### ISSUE TITLE
继续上传的逻辑问题

### ISSUE THREAD

**Issue by pisyell** [tencentyun/cos-js-sdk-v5#216]
uploadFile方法， pauseTask 后 拿着taskId 调用restartTask 后文件又从0开始上传 不能接着上次传输的大小继续？

**Comment by pisyell** [comment]
https://cloud.tencent.com/document/product/436/64960
sdk版本: cos-js-sdk-v5@1.8.3
<img width="782" alt="image" src="https://github.com/user-attachments/assets/d40b29be-039a-4aad-83fb-4356a71deea4">
文档中写会继续上传，我调用暂停下面这些方法就被取消了，后续调用restartTask 根本没任何反应
![Uploading image.png…]()

**Comment by livehigh** [comment]
续传只针对对分块上传请求，且 pauseTask 时已经完成了部分分块上传，下次 restartTask 才可以接着上次的进度继续哈
