### ISSUE TITLE
上传文件报错，官方文档没有错误code，有人解决吗？

### ISSUE THREAD

**Issue by CANONYANG** [tencentyun/cos-js-sdk-v5#24]
文件上传成功，但报400错误错误码
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>MalformedPOSTRequest</Code>
	<Message>The body of your POST request is not well-formed multipart/form-data.</Message>
	<Resource>token-up-1257006810.cos.ap-beijing.myqcloud.com</Resource>
	<RequestId>NWI0OWJjMGVfZGIyOTVkNjRfMmI2Y18yZTRjMmU=</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTY4OGQ5OWY4YWFhNjAzOTkyNDJhZmQyOTk1YWVmOWFlNmRjYjM3OWQxODI2NjkxYTUyMWFhZDNhMGE4ZmQ3Yjk=</TraceId>
</Error>

**Comment by carsonxu** [comment]
这个是怎么调用出的错？

**Comment by carsonxu** [comment]
这里有错误码说明
https://cloud.tencent.com/document/product/436/7730
