### ISSUE TITLE
authorization error 

### ISSUE THREAD

**Issue by free-free** [tencentyun/cos-js-sdk-v5#28]
上传文件的时候出现authorization error， 请问这是为什么呢

**Comment by carsonxu** [comment]
应该是sts.php返回不正确，你确认下 getAuthorization 的 callback 给 sdk 什么数据？

**Comment by free-free** [comment]
不好意思，我自己手滑了，把getAuthorization的callback参数ExpiredTime写成ExpirtedTime了。谢谢你，这么晚了，还能得到这么及时回复，非常感谢。
