### ISSUE TITLE
你们代码不审核就提交上来？一大堆bug！

### ISSUE THREAD

**Issue by XiaoliSong** [tencentyun/cos-js-sdk-v5#3]
首先server的auth.php就两个bug，一个是末尾没有加上"?>"，然后就是obj2str函数里$list创建数组不成功（至少php5.3是这样）！修改后
		function obj2str($obj)
		{
			
			$list = array(); ;
			$keyList = getObjectKeys($obj);
			$len = count($keyList);
			for ($i = 0; $i < $len; $i++) {
				$key = $keyList[$i];
				$val = isset($obj[$key]) ? $obj[$key] : '';
				$key = strtolower($key);
				$list[$i] = rawurlencode($key) . '=' . rawurlencode($val);
			}
			
			return implode('&', $list);
		}

**Comment by XiaoliSong** [comment]
另外修改后这些后依然错误，错误提示也不友善吧，直接给个error啥意思？我哪知道哪里error了！

**Comment by carsonxu** [comment]
1. auth.php 的问题：
已根据建议修改两个问题，不过，php 5.3 版本老了点吧？末尾没加 `?>` 和 `$list = [];` 在 5.6 都没问题。
这里的 auth.php 只是一个样例，真正要用，也应该加上自己网站的鉴权？

2. error 不够完善，问题已知，考虑到修改返回格式会影响老代码使用，这里会后面发个大版本修改。

**Comment by XiaoliSong** [comment]
okay。
