### ISSUE TITLE
global is not define

### ISSUE THREAD

**Issue by q986171791** [tencentyun/cos-js-sdk-v5#30]
///////////////////Here is my test code start///////////////////
const cos = require('cos-js-sdk-v5')
console.log(cos);
///////////////////Here is my test code end///////////////////

but I got a error 

in utils .js 

isBrowser:!!global.document   // This is error code

when i download dist/**.min.js file

run it again

it is good

**Comment by q986171791** [comment]
by the way,
framework:angular 6.xx
system:mac

**Comment by carsonxu** [comment]
thank you for commit issue, I will check it as soon as possiable.

**Comment by s97712** [comment]
+1, this problom still not fix?

**Comment by s97712** [comment]
This problom may in `../node_modules/cos-js-sdk-v5/src/util.js`,  it use `global` variable

**Comment by s97712** [comment]
有人解决没，没有我去隔壁阿里云逛逛了

**Comment by s97712** [comment]
@carsonxu

**Comment by carsonxu** [comment]
怎么使用产生的报错？

**Comment by s97712** [comment]
环境是angular7 通过npm使用的

**Comment by s97712** [comment]
我在构建后的文件 `../node_modules/cos-js-sdk-v5/src/util.js` 发现了几个global变量，是不是构建出问题了。

**Comment by s97712** [comment]
package.json 的main是不是应该指向dist

**Comment by carsonxu** [comment]
考虑如果用 dist 用户使用 webpack 打包的时候，会多出一份 webpack 代码 ，这里是指向 src。
我下午调试确认看看。

**Comment by s97712** [comment]
你们的构建感觉不太完善啊，其它库都有提供多个环境的构建的

**Comment by carsonxu** [comment]
已修复 global 报错，感谢反馈。多环境构建后续补充。
