### ISSUE TITLE
xhr.getResponseHeader('etag')无效的问题

### ISSUE THREAD

**Issue by AceLynn** [tencentyun/cos-js-sdk-v5#32]
demo/sts-put.html
文件里，有一行

> var ETag = xhr.getResponseHeader('etag');

上传成功后，获取请求头里的etag值？但是，在使用过程中，浏览器一直提示

> Refused to get unsafe header "etag"

请问这个该如何处理？

**Comment by carsonxu** [comment]
需要配置 CORS，ExposeHeader 加一个 ETag
https://cloud.tencent.com/document/product/436/11459

**Comment by AceLynn** [comment]
谢谢，确实是没配置好。
