### ISSUE TITLE
如何获取当前上传进度？

### ISSUE THREAD

**Issue by AceLynn** [tencentyun/cos-js-sdk-v5#33]
// 上传文件
        var uploadFile = function (file, callback) {
            var Key = 'dir/' + file.name; // 这里指定上传目录和文件名
            getAuthorization({Method: 'PUT', Key: Key}, function (err, info) {
                xxx
                var xhr = new XMLHttpRequest();
                xhr.open('PUT', url, true);
                xxx
                xhr.onload = function () {
                    if (xhr.status === 200 || xhr.status === 206) {
                        var ETag = xhr.getResponseHeader('etag');
                        callback(null, {url: url, ETag: ETag});
                    } else {
                        callback('文件 ' + Key + ' 上传失败，状态码：' + xhr.status);
                    }
                };
                xhr.onerror = function () {
                    callback('文件 ' + Key + ' 上传失败，请检查是否没配置 CORS 跨域规则');
                };
                xhr.send(file);
            });
        };

想请问一下，上传文件如何获取当前上传进度，好做个进度条。查看了一下文档，暂未找到相关api。用搜索的xhr.upload.onprogress，获取的当前event.loaded（已传大小）直接和event.total（文件总大小）一样，就是进度直接100%了，然而看接口状态还是pending，依然还在传送中？

**Comment by carsonxu** [comment]
如果用 SDK ，可以传入 onProgress 回调：

**Comment by carsonxu** [comment]
这里是原生 ajax 可以使用 xhr.onprogress 监听进度，回调的事件 e 有个 e.loaded

**Comment by AceLynn** [comment]
是使用的onprogress，试了下直接xhr.onprogress不行。
xhr.upload.onprogress可以；但是e.loaded直接和e.total大小一样了……正常理解，e.loaded应该是变化的，最后才一样。

**Comment by carsonxu** [comment]
我测试了下，确实是 xhr.upload.onprogress，但是 e.loaded 和 e.total 大小一样应该是上传完成了。
你试试大文件，total 是固定值，loaded 是一直增加。e.total 会和 file.size 是一致。

**Comment by AceLynn** [comment]
测试了一个大文件，loaded确实会增加了，而且速度很快。只是数值完成的时候，接口（http://bucket xxxx.cos.ap-xxxx.myqcloud.com/xxxx/xxxxxx.apk）那边仍然显示的pending的状态；猜测loaded增加的对应是扫描文件的状态？
就像qq邮件的附件，扫描速度挺快，扫描完了，才开始真正的数据传送？
对比接口显示的pending状态，pending状态的持续时间基本= 文件大小 / 我这边的上传速度。比如我传了20M的文件，我这边上传受限制了，只有100k左右，大约要4分钟左右传送完。差不多这个时间，接口才会变成200状态。查看请求，timing那边，4分钟大部分时间都耗费在Wating（TTFB）上。
不知道你测试的时候会不会这样。如果是我猜测的，那返回的进度就不对了，并不是上传的进度。

**Comment by carsonxu** [comment]
loaded 不是扫描进度，他是原生特性，不会对文件有扫描过程。
loaded 是客户端发出去多少字节，还得等接口处理完文件新增的一些逻辑，请求才会结束。
看你说的这个，感觉有可能是走了代理服务，你已经把数据全部发出去了，代理服务缓存的数据还在慢慢传到COS API？

**Comment by carsonxu** [comment]
这里正式使用，就按照 e.loaded / e.total 计算就行，剩下的时间没办法再提供进度的。

**Comment by AceLynn** [comment]
试了下……确实是代理的问题。开发中开着fiddler……关掉测试后，进度就对的上了。非常感谢。
