### ISSUE TITLE
server/sts.php 返回报错 400 StrategyResourceInvalid

### ISSUE THREAD

**Issue by stevieyu** [tencentyun/cos-js-sdk-v5#34]
message: (60024)you are not resource owner
找遍文档找不到处理方法

**Comment by carsonxu** [comment]
你传的是什么resource?

**Comment by carsonxu** [comment]
sts是这个文档https://cloud.tencent.com/document/product/598/13896

**Comment by stevieyu** [comment]
@carsonxu 我看代码里面的参数, 不是这个文档吗? https://cloud.tencent.com/document/product/436/14048

**Comment by carsonxu** [comment]
是的两个都可以，第一个是sts文档，第二个是用sts访问cos的文档。

**Comment by stevieyu** [comment]
@carsonxu 可是我只是把代码的config的参数改了 换上自己的 SecretId SecretKey Bucket Region 
AllowPrefix 为 * 
响应内容就为这个了
```json
{"code":4000,"message":"(60024)you are not resource owner","codeDesc":"StrategyResourceInvalid "}
```

**Comment by carsonxu** [comment]
sts接口只支持主账号密钥访问。

**Comment by stevieyu** [comment]
![image](https://user-images.githubusercontent.com/8325201/45199509-a3f32d00-b29e-11e8-99fe-6518e76b570e.png)
这个地方的密钥是主账号吧?里面只有一个

**Comment by carsonxu** [comment]
那是否申请的资源不属于该帐号

**Comment by stevieyu** [comment]
@carsonxu 自己的qq号登录进去,创建的cos的 bucket 和 api密钥, 这两个都同属于一个qq, 应该不算不属于吧?  还是说需要哪里加个关联, 把cos跟api密钥关联起来?

**Comment by carsonxu** [comment]
不需要关联，同一账号创建的就算，你教教一个工单具体看看？

**Comment by stevieyu** [comment]
对了, 我用这个 https://github.com/tencentyun/cos-php-sdk-v5 可以上传文件,且无报错

**Comment by ss22219** [comment]
参数调整一下解决了
`$bucket = $bucket . '_' . $appid`
