### ISSUE TITLE
我在reactnative使用不了，说是有jquery，而reactnative是可以使用ajax的

### ISSUE THREAD

**Issue by carsonxu** [tencentyun/cos-js-sdk-v5#35]
_Originally posted by @luoshuisheng in https://github.com/tencentyun/cos-js-sdk-v5/issues/22#issuecomment-430959318_

**Comment by luoshuisheng** [comment]
是支持文件上传的，我直接调用API吧

**Comment by luoshuisheng** [comment]
> jquery 应该就是用 ajax 发请求，这里是否 RN 支持的 ajax 没支持文件上传 @luoshuisheng

我这边已经后端返回临时秘钥给客户端了, 客户端还要根据拿到的临时秘钥计算生成Authorization然后才能调用图片上传接口吗?

**Comment by carsonxu** [comment]
对，这里有例子 https://cloud.tencent.com/document/product/436/9067
也可以参考当前 demo/sts-put.html

**Comment by luoshuisheng** [comment]
> 对，这里有例子 https://cloud.tencent.com/document/product/436/9067
> 也可以参考当前 demo/sts-put.html
请问一下客户端拿到临时秘钥怎么生成Authorization?还需要调接口?

**Comment by luoshuisheng** [comment]
> 对，这里有例子 https://cloud.tencent.com/document/product/436/9067
> 也可以参考当前 demo/sts-put.html

请问一下客户端拿到临时秘钥怎么生成Authorization?还需要调接口?

**Comment by carsonxu** [comment]
可以调用 SDK 的静态方法：COS.getAuthoorization：
https://cloud.tencent.com/document/product/436/12260#cos.getauthorization
也可以在源码里把这部分计算代码，单独拿出来自己用。

**Comment by luoshuisheng** [comment]
> 可以调用 SDK 的静态方法：COS.getAuthoorization：
> https://cloud.tencent.com/document/product/436/12260#cos.getauthorization
> 也可以在源码里把这部分计算代码，单独拿出来自己用。

谢谢, 集成不了sdk, 只能拿出来用了

**Comment by luoshuisheng** [comment]
> 可以调用 SDK 的静态方法：COS.getAuthoorization：
> https://cloud.tencent.com/document/product/436/12260#cos.getauthorization
> 也可以在源码里把这部分计算代码，单独拿出来自己用。

临时秘钥后端可以生成, 签名后端怎么生成呢?想把签名直接生成返回客户端, 客户端拿到签名去调接口,而不是客户端还要拿到临时秘钥再生成签名

**Comment by carsonxu** [comment]
参考 server/sts-auth.js 或者 server/sts-auth.php

**Comment by luoshuisheng** [comment]
> 参考 server/sts-auth.js 或者 server/sts-auth.php

看了一下, 这里面的调用临时秘钥接口就是qcloud-cos-sts做的事吧, 
我现在的做法是:生成临时秘钥再使用计算签名:
```
sts.getCredential(options, function(dataCredentials) {
  let tempKeys = dataCredentials.data;
  var err = null;
  var data;
  var pathname = req.body.pathname || req.query.pathname || '';
              var Key = pathname.substr(0, 1) === '/' ? pathname.substr(1) : pathname;
              var opt = {
                  SecretId: tempKeys.credentials.tmpSecretId,
                  SecretKey: tempKeys.credentials.tmpSecretKey,
                  Method: req.body.method || req.query.method,
                  Key: Key,
                  Query: req.body.query || req.query.method || {},
                  Headers: req.body.headers || req.query.headers || {},
              };
              data = {
                  Authorization: COS.getAuthorization(opt),
                  XCosSecurityToken: tempKeys['credentials'] && tempKeys['credentials']['sessionToken'],
              };
    res.send(err || data);
});
```

这样的写法,可以吗?之后在客户端调用上传图片的接口, 在header里面加上Authorization?
我这样试了一下, 发现是The Access Key Id you provided does not exist in our records

**Comment by carsonxu** [comment]
最终请求cos时，加上两个header:
authorization
x-cos-security-token
对应callback的两个字段

**Comment by waterluo** [comment]
> 最终请求cos时，加上两个header:
> authorization
> x-cos-security-token
> 对应callback的两个字段

```
<?xml version='1.0' encoding='utf-8' ?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The Signature you specified is invalid.</Message>
    <StringToSign>sha1
1539886122;1539887022
f625835bdc9539c2ad96438f06c536b39d8810a0
</StringToSign>
    <FormatString>put
```
使用put请求的时候, 还是报错

**Comment by waterluo** [comment]
> 最终请求cos时，加上两个header:
> authorization
> x-cos-security-token
> 对应callback的两个字段

自己做了一个获取签名的接口, 然后使用postman获取签名, 拿到签名之后再调用cos上传的接口, 报错
```
<Code>SignatureDoesNotMatch</Code>
    <Message>The Signature you specified is invalid.</Message>
```

**Comment by carsonxu** [comment]
参考这个例子：demo/sts-put.html
页面需要传对应 method、pathname 给你的签名接口

**Comment by waterluo** [comment]
> 参考这个例子：demo/sts-put.html
> 页面需要传对应 method、pathname 给你的签名接口

传了, 拿到签名上传还是403
