### ISSUE TITLE
此SDK支持IE9浏览器吗

### ISSUE THREAD

**Issue by lance-ding** [tencentyun/cos-js-sdk-v5#36]
文档中提到使用了HTML5的特性，由于没有查看源码不确定使用了哪些，SDK是否支持IE9浏览器？

谢谢.

**Comment by carsonxu** [comment]
上传接口需要用FilderReader，最低支持ie10

**Comment by lance-ding** [comment]
> 上传接口需要用FileReader，最低支持ie10

好的，知晓了，谢谢
