### ISSUE TITLE
Body的校验在跨iframe的时候出错

### ISSUE THREAD

**Issue by IveChen** [tencentyun/cos-js-sdk-v5#38]
在使用富文本编辑器ueditor进行开发的时候，需要使用sliceUploadFile进行上传。然后发现一个问题，因为ueditor进行上传的页面使用的是iframe的方式，所以如果使用最外层容器即top.COS进行上传的时候，虽然params.Body是属于File，但不属于top.File(即下面的global.File)，所以导致抛出params.body error。
```
var getFileSize = function (api, params, callback) {
    var size;
    if (util.isBrowser) {
        if (typeof params.Body === 'string') {
            params.Body = new global.Blob([params.Body]);
        }
        if (params.Body instanceof global.File || params.Body instanceof global.Blob) {
            size = params.Body.size;
        } else {
            callback({error: 'params body format error, Only allow File|Blob|String.'});
            return;
        }
    }
```
我只能在每个iframe都引入文件包，并且对于ueditor使用js创建的iframe 也得补上js引用。。。
所以能否换个方式来校验prams.body(比如加上校验是否含有name,size属性之类，或者有一个自定义的校验方式？)。。

**Comment by carsonxu** [comment]
什么浏览器？
我这边好像没出现，如果我把 global 去掉是否没问题？

**Comment by carsonxu** [comment]
出问题的浏览器是否安装了 chrome 插件 AdGuard，并且半年没更新 js sdk 版本了？

**Comment by IveChen** [comment]
就是ueditor经常使用iframe的intput:file 来进行上传文件。
但是iframe里的input:file生成的file对象是属于 iframe.contentWindow.File 而不属于最外层的window.File
因此你这里去掉global没什么用。执行的时候this还是最外层的window

算了。。反正属于小众需求。。我自己改sdk好了。。

**Comment by carsonxu** [comment]
明白了，谢谢反馈，今天修复

**Comment by IveChen** [comment]
已看到修复，谢谢大佬。
看到是使用constructor.name 来进行判断，学到了一个新的东西，但是查了下 [MDN ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) 好像在IE有兼容性问题。

**Comment by carsonxu** [comment]
已再次修复，用了 Body.toString() === '[object File]'
