### ISSUE TITLE
关于分片上传我这里有两个不明白的地方？？

### ISSUE THREAD

**Issue by shawn805** [tencentyun/cos-js-sdk-v5#39]
首先Authorization是一串这样的签名：q-sign-algorithm=sha1&q-ak=AKIDYw63nIGcR2PYTAosseCWcU9ZljTyJH5k&q-sign-time=1545045621;1545047481&q-key-time=1545045621;1545047481&q-header-list=host&q-url-param-list=&q-signature=a7e287c8fa1704c35fdb8cace9b2956ea6d056c4

这个官方提供的第一种方式：这个是向后台拿到临时密钥，在分片上传的时候（每一个请求）Authorization都是不一样的，我可以理解为每次请求的时候由这个包计算出来的。这种方式是可以走通的。
![image](https://user-images.githubusercontent.com/27723906/50228145-3fd61e00-03e2-11e9-9674-c307ef5f6bdc.png)

这个官方提供的第二种方式：问题就是这个第二种方式了，如果是在分片上传的情况下也是多个请求，但是签名就只会向后端拿取一次，签名也只能用一次（后面的请求就失效了）。所以如果是后端生成签名的方式的话，这种请求怎么处理。
![2](https://user-images.githubusercontent.com/27723906/50228955-28983000-03e4-11e9-87a5-21da89d24823.jpg)

**Comment by carsonxu** [comment]
格式二这种，分片上传会多次执行 getAuthorization
每次进入可能是不一样的 Method、Key

**Comment by shawn805** [comment]
多次执行getAuthorization也就是会多次向后端请求签名（这么理解是对的吗）
我可以把这个理解为对象键（就是key）bucket1-1250000000.cos.ap-guangzhou.mycloud.com/doc1/pic1.jpg
![image](https://user-images.githubusercontent.com/27723906/50230866-79aa2300-03e8-11e9-92ce-d607aaf97338.png)

**Comment by shawn805** [comment]
> 格式二这种，分片上传会多次执行 getAuthorization
> 每次进入可能是不一样的 Method、Key
多次执行getAuthorization也就是会多次向后端请求签名（这么理解是对的吗）
我可以把这个理解为对象键（就是key）bucket1-1250000000.cos.ap-guangzhou.mycloud.com/doc1/pic1.jpg
![image](https://user-images.githubusercontent.com/27723906/50231249-4e740380-03e9-11e9-9295-d0e5bfd3641f.png)

**Comment by carsonxu** [comment]
对，分片上传，会多次请求到后端
这里进来的Key有点不严谨，其实应该叫做Pathname

**Comment by shawn805** [comment]
> 对，分片上传，会多次请求到后端
> 这里进来的Key有点不严谨，其实应该叫做Pathname

那这样不会有问题吗，我每次分片上传的时候（向腾讯云服务器请求一次）也会向我们服务器后台请求一次拿签名，这样合理吗？

**Comment by carsonxu** [comment]
这样不会有问题，方式一会更合适，只请求一个临时密钥。有效期内都不用发请求

**Comment by shawn805** [comment]
好的，请问这个包什么时候会再更新

**Comment by shawn805** [comment]
> 这样不会有问题，方式一会更合适，只请求一个临时密钥。有效期内都不用发请求

好的，明白了，请问这个包什么时候会再更新

**Comment by carsonxu** [comment]
是指更新什么内容？
一周内会有更新的版本，优化一些细节
