### ISSUE TITLE
Slice Upload File不支持指定ContentType

### ISSUE THREAD

**Issue by w1ida** [tencentyun/cos-js-sdk-v5#40]
建议能自动判断当body为File类型时，自动指定ContentType为file.type

**Comment by carsonxu** [comment]
前端没默认指定，后端会根据文件命名的后缀名指定一个 Content-Type。
比如 a.zip 会指定 application/zip
前端自动指定，我们讨论下看

**Comment by carsonxu** [comment]
上周有个 bug 导致分片上传会有 Content-Type application/xml，请更新最新版本 sdk js

**Comment by w1ida** [comment]
原来如此，刚好用的上周的sdk没更新，感谢

**Comment by carsonxu** [comment]
用例没覆盖没检查出来，已补充 Content-Type 的测试用例，感谢反馈~

**Comment by carsonxu** [comment]
麻烦再更新一个版本，上次修复 Content-Type 问题，还有一些浏览器（chrome 69）没处理好。更新 0.5.8 就行
