### ISSUE TITLE
关于这个sdk不同浏览器的问题

### ISSUE THREAD

**Issue by zhibinm** [tencentyun/cos-js-sdk-v5#43]
在本地测试，本人谷歌浏览器版本 71.0.3578.80（正式版本） （32 位）测试正常，放到线上运行后，也可以的。后来另外一个同事使用，他电脑 平时用360浏览器，使用上传时一直返回403，后来重新下载了个谷歌浏览器又可以用，就是360浏览器用不了，又找了一台电脑 ，电脑用的也是谷歌浏览器，版本不是最新的，也同样返回403，<Code>SignatureDoesNotMatch</Code><Message>The Signature you specified is invalid.</Message>，把谷歌浏览器升级到最新的版本，又能正常使用，请问这个问题怎么破。

**Comment by carsonxu** [comment]
这个是 0.5.7 一个 bug，0.5.8 已修复
