### ISSUE TITLE
分片上传函数的onProgress属性只在上传完成的时候才被调用

### ISSUE THREAD

**Issue by GtGuiZhou** [tencentyun/cos-js-sdk-v5#44]
分片上传函数的onProgress属性只在上传完成的时候才被调用，也就是说从始至终只被调用一次，不能显示上传过程

**Comment by carsonxu** [comment]
什么情况下出现的？有没有页面可以看看？

**Comment by chencanbin** [comment]
我也发现了这个情况，请问能解决吗

**Comment by carsonxu** [comment]
@chencanbin 什么浏览器？
试试实例化时，配置：ProgressInterval: 1,
调用 sliceUploadFile 传 SliceSize: 0
