### ISSUE TITLE
403报错

### ISSUE THREAD

**Issue by michael2043** [tencentyun/cos-js-sdk-v5#46]
java:
![360 17040509504833](https://user-images.githubusercontent.com/4134458/52570810-410a5100-2e4f-11e9-9625-631629fc97a1.png)
js:
![360 17001015365627](https://user-images.githubusercontent.com/4134458/52570756-16b89380-2e4f-11e9-8ba9-a1b5ec159710.png)
浏览器：
![360 17060219444654](https://user-images.githubusercontent.com/4134458/52570710-f557a780-2e4e-11e9-8d1b-fac85cbe521d.png)

**Comment by carsonxu** [comment]
是否没配置存储同个CORS

**Comment by carsonxu** [comment]
是否没配置存储同个CORS

**Comment by michael2043** [comment]
> 是否没配置存储同个CORS

![360 18280504497358](https://user-images.githubusercontent.com/4134458/52604241-029f8100-2ea5-11e9-9ede-513aa5c4ec8e.png)

**Comment by carsonxu** [comment]
没配置当前页面的http://localhost:8080

**Comment by huangzizai** [comment]
这个问题怎么解决的

**Comment by carsonxu** [comment]
@huangzizai 403 一般是签名不对/权限不足。
需要确认 policy 是不是没包含对应的 action？
如果没找出原因，可以到腾讯云提工单贴 x-cos-request-id 排查。

**Comment by huangzizai** [comment]
@carsonxu 谢谢！
