### ISSUE TITLE
OPTIONS请求被拦截

### ISSUE THREAD

**Issue by zh244135370** [tencentyun/cos-js-sdk-v5#48]
前端Vue通过cos-js-sdk-v5构造之后发送请求，浏览器会先发出一个OPTIONS请求，然后返回403跨域被直接拦截，控制台也没有配置OPTIONS跨域的方式，这种要怎么处理，只能后端Java上传吗？
`import COS from 'cos-js-sdk-v5'`

`this.cos = new COS({`
       `    getAuthorization: function (options, callback) {`
                       ` vueHttp.getTmpSecret().then(res => {`
                            `callback({`
                                `TmpSecretId: res.data.secretId,`
                                `TmpSecretKey: res.data.secretKey,`
                                `XCosSecurityToken: res.data.sessionToken,`
                                `ExpiredTime: res.data.expiredTime`
                           ` })`
                       ` })`
                   ` }`
                `})`

`_this.cos.sliceUploadFile({`
                            `Bucket: _this.Bucket,`
                           ` Region: _this.Region,`
                           ` Key: item.cname,`
                            `Body: item`
                        `}, function (err, data) {`
                            `console.log(err, data)`
                        })`

**Comment by zh244135370** [comment]
@carsonxu

**Comment by carsonxu** [comment]
到控制台设置存储桶的 CORS 配置：
![image](https://user-images.githubusercontent.com/24862812/53464518-7d5fc300-3a85-11e9-9aee-8ffaff207acb.png)

**Comment by zh244135370** [comment]
> 到控制台设置存储桶的 CORS 配置：
> ![image](https://user-images.githubusercontent.com/24862812/53464518-7d5fc300-3a85-11e9-9aee-8ffaff207acb.png)
