### ISSUE TITLE
有什么办法限制前端上传的文件尺寸

### ISSUE THREAD

**Issue by untsop** [tencentyun/cos-js-sdk-v5#5]
是否有类似七牛的 policy 配置的方案允许对前端上传进行一些限制，包括文件尺寸，权限等。

**Comment by carsonxu** [comment]
可以考虑从上传的入口做限制，我确认下有没有这样的策略。

**Comment by carsonxu** [comment]
确认了没有这个策略，建议在传给 SDK 之前判断阻止上传。

**Comment by untsop** [comment]
前端如何判断阻止上传？用户可以直接凭签名直接上传大尺寸文件到 COS，直到耗尽服务资源，导致服务欠费停服。这是潜在的安全威胁。

**Comment by untsop** [comment]
当然我是指不怀好意的用户，如果刻意利用这个缺陷的话，可以实现这个的效果。

实际上这个威胁目前在所有使用了前端直接上传的 COS 的服务的网站上都有，理论所有这些网站都有可能被恶意上传大尺寸的文件，耗尽账号余额，直至停服。

因此我建议应该按照安全问题来修复它。

**Comment by Galen-Yip** [comment]
这个是可以通过签名做到的 签名的策略里可以限制文件大小

**Comment by untsop** [comment]
@Galen-Yip 可有相关文档的链接？我这边搜索未能找到相关的策略（限制文件大小的策略）

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cos-js-sdk-v5/blob/master/server/auth.php
这个demo里面有把header加到签名计算的处理，需要在前端发请求获取签名时，把要发请求的content-length传过来，加到签名计算里。

如果前端使用当前sdk，我今晚更新代码，提供一个签名带上header参数的示例。
