### ISSUE TITLE
putObject 中的onProgress 函数只能在每次上传完的时候才调用

### ISSUE THREAD

**Issue by chencanbin** [tencentyun/cos-js-sdk-v5#50]
putObject 中的onProgress 函数只能在每次上传完的时候才调用

**Comment by chencanbin** [comment]
![image](https://user-images.githubusercontent.com/6744909/53899734-d75c1c00-4075-11e9-92fd-eb6273f3eaaf.png)

**Comment by chencanbin** [comment]
@carsonxu

**Comment by carsonxu** [comment]
返回频率默认是约 1 秒一次。
试试配置：ProgressInterval: 1 // 单位 ms
