### ISSUE TITLE
请问想要支持IE8,IE9怎么办？比如如何结合webuploader?

### ISSUE THREAD

**Issue by HelloHxz** [tencentyun/cos-js-sdk-v5#52]
请问想要支持IE8,IE9怎么办？比如如何结合webuploader? 或者有没有其他方式去实现？

**Comment by carsonxu** [comment]
支持低版本ie可以不使用sdk参考demo/sts-form.html
如果用webuploader可以参考demo/sts-put.html

**Comment by HelloHxz** [comment]
好的  谢啦~~ 因为文档没有说明 所以提了issues
