### ISSUE TITLE
怎么配合微信网页开发的wx.chooseImage()接口使用？

### ISSUE THREAD

**Issue by yuzifu** [tencentyun/cos-js-sdk-v5#54]
本来是使用原生input标签配合cos上传文件的，但发现实现好的功能在微信开发者工具调试正常，在真机下却只能选择一个文件，于是转到JSSDK的wx.chooseImage()接口实现。
wx.chooseImage()接口得到的是图片localIds，并且没看到有获取File对象的接口，cos-js-sdk-v5也不支持根据图片的localIds来上传文件。
请问有什么解决方案吗？

**Comment by carsonxu** [comment]
1. 通过微信接口选文件，上传到微信线上存储
2. 上传完成通知你自己的服务端去拉取代码，再传给COS，传完再返回成功失败给前端

**Comment by yuzifu** [comment]
@carsonxu 谢谢!
