### ISSUE TITLE
上传经常报错get ETag error, please add "ETag" to CORS ExposeHeader setting

### ISSUE THREAD

**Issue by zhanghpeiyong** [tencentyun/cos-js-sdk-v5#56]
少数时候报错，大多数时候上传正常，已经有配置ETag等配置项
get ETag error, please add "ETag" to CORS ExposeHeader setting

**Comment by carsonxu** [comment]
分片上传需要到控制台设置 CORS ExposeHeader 加一个 ETag

**Comment by carsonxu** [comment]
加了就不会有这个错误的，你确认下是否给对应 bucket 加成功。

**Comment by zhanghpeiyong** [comment]
> 加了就不会有这个错误的，你确认下是否给对应 bucket 加成功。

加了的，没加的话就不会只是偶尔报这个错误了，没加的情况下就是必现的了

**Comment by carsonxu** [comment]
你应该是小文件用了 cos.putObject
大文件用 cos.sliceUplaodFile
cos.sliceUplaodFile 才会需要 ETag
你贴一下你存储桶名称？

**Comment by zhanghpeiyong** [comment]
> 你应该是小文件用了 cos.putObject
> 大文件用 cos.sliceUplaodFile
> cos.sliceUplaodFile 才会需要 ETag
> 你贴一下你存储桶名称？

mhjy-client-1251001060

**Comment by carsonxu** [comment]
你 CORS 配置有两个，命中了第一个 Expose-Headers 空的一项，可以删除掉这一项
