### ISSUE TITLE
putObject提示403

### ISSUE THREAD

**Issue by rongdongwang** [tencentyun/cos-js-sdk-v5#57]
putObject提示403，看了一下请求头Authorization，发现时间相关的字段都是NAN，看代码getSkewTime这个函数 return Date.now() + (offset || 0)是否应该改成    return Date.now().getTime() + (offset || 0)呢？
浏览器版本73.0.3683.86（正式版本） （64 位）

**Comment by rongdongwang** [comment]
我改成Date.now().getTime()后上传就成功了

**Comment by carsonxu** [comment]
Date.now() 返回的应该是一个 number，不能在 .getTime()

**Comment by rongdongwang** [comment]
> Date.now() 返回的应该是一个 number，不能在 .getTime()

了解，找到原因了，我们用了Date.js,覆盖了原生Date的方法了
