### ISSUE TITLE
v4 的 cos.uploadFile 方法没有了怎么办？

### ISSUE THREAD

**Issue by weituotian** [tencentyun/cos-js-sdk-v5#6]
求重新加上，不然我换v5 就要把调用的方法都改了。
要做好兼容处理啊

**Comment by carsonxu** [comment]
没有去掉的，你确认一下？

**Comment by weituotian** [comment]
我看到v5的demo.js 中只有 uploadFiles的方法

v4的上传程序示例,
```
var myFolder = '/111/';//需要操作的目录
var successCallBack = function (result) {
    $("#result").val(JSON.stringify(result));
};

var errorCallBack = function (result) {
    result = result || {};
    $("#result").val(result.responseText || 'error');
};

var progressCallBack = function(curr){
    $("#result").val('uploading... curr progress is '+curr);
};

$('#js-file').off('change').on('change', function (e) {
    var file = e.target.files[0];
    cos.uploadFile(successCallBack, errorCallBack, progressCallBack, bucket, myFolder+file.name, file, 0);
    return false;
});
```

**Comment by carsonxu** [comment]
v5，v4是两个不一致的sdk

**Comment by weituotian** [comment]
所以说我想把sdk从v4升级到v5 , 但是因为v5没有uploadFile这个方法，我还要重写修改我业务代码中调用上传的部分，这样做不到无缝升级，一换sdk就全盘报错了

**Comment by carsonxu** [comment]
只调用了uoloadFile方法吗？

**Comment by carsonxu** [comment]
可以写一个适配代码前端，sdk本身不适合加兼容。

**Comment by weituotian** [comment]
能不能做一个迁移的js，提供和v4的接口一模一样的调用方法，然后内部用的是v5的sdk
求！

**Comment by weituotian** [comment]
你看jQuery都有jQuery Migrate辅助迁移的
腾讯cos这么专业也该提供一个呗

**Comment by carsonxu** [comment]
那你为啥换v5？
这个适配的js工作量太大了，很不好维护，接口改了要更新，而且里面有些特性是不能完全兼容。不考虑做这个兼容。

**Comment by weituotian** [comment]
可以先做uploadFile等常用的函数先，新特性的话如果v4没有可以不做

**Comment by hgwang** [comment]
v4生成的access_url访问的时候报`You do not have permission to get URL '/h5/trim.38A3D827-193A-4528-9A22-627CA06338E8.MOV' from this server.`类似的错误，如何解决？

**Comment by carsonxu** [comment]
你的文件应该是私有读，需要在url加一个sign参数带上签名。
v4签名参考https://github.com/tencentyun/cos-js-sdk-v4/blob/master/demo/index.html
