### ISSUE TITLE
上传文件错误

### ISSUE THREAD

**Issue by experdot** [tencentyun/cos-js-sdk-v5#60]
电脑端可以上传成功，移动端部分机型报错，返回的错误信息如下
``` json
{"error":"error","headers":{}}
```

使用的是分片上传, 代码如下：
``` javascript
            this.getCOS().sliceUploadFile({
                Bucket: this.metadata.Bucket,
                Region: this.metadata.Region,
                Key: this.getFolderName() + GUID.generate() + "_" + file.name,
                Body: file
            }, function (err, data) {
            });
```

**Comment by carsonxu** [comment]
CORS怎么配置的？
AllowHeaders需要配*

**Comment by experdot** [comment]
@carsonxu 
![image](https://user-images.githubusercontent.com/9404172/58786190-9c886680-8619-11e9-978a-f5a478876a19.png)
最宽松的策略。

**Comment by carsonxu** [comment]
什么浏览器版本会出错？

**Comment by experdot** [comment]
@carsonxu 

### Overview
- 测试了几种机型，IOS 下微信和 Safari 均可以正常上传。
- 安卓部分机型的微信内置浏览器上传失败，自带浏览器上传成功。
- 上传失败时返回的错误信息一样`{"error":"error","headers":{}}`
- 站点没有启用 Https

### 微信内上传失败的机型
- 华为P30
- Huawei Kirin980
- 坚果 Pro OD103

### 微信内上传成功的机型
- 小米 Redmi 7

**Comment by Creat155** [comment]
@experdot 在浏览器上测都可以正常上传，但是在真机上VIVO可以，苹果和华为不行，请问你是怎么在真机上看到接口返回的错误信息的呢？

**Comment by carsonxu** [comment]
能否真机调试，提供一个RequestId？

**Comment by carsonxu** [comment]
加我Q具体一起看看

**Comment by experdot** [comment]
> @experdot 在浏览器上测都可以正常上传，但是在真机上VIVO和华为可以，苹果不行，请问你是怎么在真机上看到接口返回的错误信息的呢？

上传失败时，浏览器会把错误消息 alert 给用户

**Comment by experdot** [comment]
> 加我Q具体一起看看459452372
已经加了

**Comment by experdot** [comment]
> 能否真机调试，提供一个RequestId？

有在线的测试环境可以复现，但那是客户的环境，需要私聊发你，怎么做

**Comment by carsonxu** [comment]
加我 Q @experdot

**Comment by experdot** [comment]
@carsonxu 加了，你看一下好友申请
