### ISSUE TITLE
签名url限定了httpMethod，但是同一个上传请求会发多次不同 method 的request导致上传失败

### ISSUE THREAD

**Issue by bleehome** [tencentyun/cos-js-sdk-v5#63]
经观察，上传一个文件的时候会调用好几次的
GET, POST, PUT 请求，但是同一个签名只允许一个Method，于是：

new COS({
getAuthorization : (options, callback) => {
 if(options.method == 'GET') {
callback(signGET)
} else if(options.method == 'POST') {
callback(signPOST)
}
... callback(signXXX)
}
})

其中 signXXX 为类似于下面的字符串，使用ajax请求从后台获取
q-sign-algorithm=sha1&q-ak=AKIDvlT5Zw3b4NVUJGjGF4kHdpqfOwKXpjeN&q-sign-time=1561468093;1561486093&q-key-time=1561468093;1561486093&q-header-list=&q-url-param-list=&q-signature=ce6b4cf3441c944f5098ee0884d3ef2fa358464d

但是 如果我不给 getAuthorization 回调传个 ExpiredTime 就再也不会调getAuthorization 方法，如果传了到是可以工作，但每个分片都要重新签名一次。

能不能给   COS 添加一个方法，允许手动强制让签名过期呢？

**Comment by carsonxu** [comment]
上传有两个，putObject 是单请求，sliceUploadFile 是复杂的分片请求。
如果 getAuthorization 返回签名，签名要根据 options.Method、options.Pathname 计算
如果 getAuthorization 返回临时密钥，密钥获取时 action 要写上以下几个：
```
// 简单上传
'name/cos:PutObject',
'name/cos:PostObject',
// 分片上传
'name/cos:InitiateMultipartUpload',
'name/cos:ListMultipartUploads',
'name/cos:ListParts',
'name/cos:UploadPart',
'name/cos:CompleteMultipartUpload'
```
