### ISSUE TITLE
找不到md5模块

### ISSUE THREAD

**Issue by kaysonli** [tencentyun/cos-js-sdk-v5#66]
运行时报错：
 ERROR  Failed to compile with 1 errors                                                                                                                                                                      19:47:59
This relative module was not found:

* ../lib/md5 in ./node_modules/cos-js-sdk-v5/src/util.js

在node_modules/cos-js-sdk-v5/lib 下根本没有这个模块

**Comment by Jinqn** [comment]
https://github.com/tencentyun/cos-js-sdk-v5/blob/master/lib/md5.js
有这个文件的，你那边是怎么调用导致出错？

**Comment by kaysonli** [comment]
> https://github.com/tencentyun/cos-js-sdk-v5/blob/master/lib/md5.js
> 有这个文件的，你那边是怎么调用导致出错？

就是用npm install cos-js-sdk-v5 安装的，里面没有这个文件

**Comment by Jinqn** [comment]
测试了下有的，用的是什么版本？是否被什么东西删除了？

**Comment by kaysonli** [comment]
找到原因了，安装的时候系统提示安全威胁，隔离了文件
![image](https://user-images.githubusercontent.com/1317521/65242842-aa56ee80-db19-11e9-975e-1d6119b8847a.png)
