### ISSUE TITLE
大哥们，没有React Native版本的嘛

### ISSUE THREAD

**Issue by EnkeChan** [tencentyun/cos-js-sdk-v5#67]

**Comment by carsonxu** [comment]
没，暂不支持

**Comment by carsonxu** [comment]
封装了一个 React Native的SDK，目前只提供上传下载功能
https://github.com/tencentyun/cos-xml-react-native
@EnkeChan

**Comment by Arnoldnuo** [comment]
> https://github.com/tencentyun/cos-xml-react-native

项目找不到了，删除了？
