### ISSUE TITLE
请教一下文件相同内容但是名称不同,如何处理?

### ISSUE THREAD

**Issue by 23233** [tencentyun/cos-js-sdk-v5#68]
我想的方案就是计算内容的md5,我也在sdk中看到了类似的方法,并且还内置执行了,但是我无法通过一个办法获取到这个已经计算过的md5.

最终想要达到的目的就是 相同内容的文件 生成相同ID的key 

请教一下,如何才能实现此操作?

**Comment by carsonxu** [comment]
传不同 Key

**Comment by lomocc** [comment]
你好，请问能不能将 `getFileMd5` 暴露出来，方便用户获取文件的 `MD5` 值?

> 传不同 Key

**Comment by lomocc** [comment]
> 你好，请问能不能将 `getFileMd5` 暴露出来，方便用户获取文件的 `MD5` 值?
> 
> > 传不同 Key

或者如果 `Key` 为空时（或增加其他额外参数判断），使用文件的 `MD5` 值作为 `Key`，你看可以吗？
