### ISSUE TITLE
这块的代码不调用是什么鬼？

### ISSUE THREAD

**Issue by 401825317** [tencentyun/cos-js-sdk-v5#69]
![image](https://user-images.githubusercontent.com/19526136/67559678-ff56d780-f74b-11e9-990d-5e9c8b29334c.png)
![image](https://user-images.githubusercontent.com/19526136/67559715-15fd2e80-f74c-11e9-98c8-2035d5b32e79.png)

已经排除引用，上下文执行的问题了

**Comment by carsonxu** [comment]
new不会进入
调用每个API方法才会。比如调用cos.getBucket
