### ISSUE TITLE
Failed to Parse XML Document Reason: 文件提前结束。Line:1 Column: 1

### ISSUE THREAD

**Issue by hgwang** [tencentyun/cos-js-sdk-v5#7]
环境：iOS10.3 微信6.6.1
调用v5版本的sliceUploadFile方法时报错
`Failed to Parse XML Document Reason: 文件提前结束。Line:1 Column: 1`

**Comment by carsonxu** [comment]
看不出原因，给一下RequestId

**Comment by carsonxu** [comment]
这里看下是否没有配置 CORS ExposeHeaders: Etag，或者 sliceUploadFile 了文件大小为 0 的文件
