### ISSUE TITLE
使用uploadFiles进行批量上传时，部分options请求会失败

### ISSUE THREAD

**Issue by remote-star** [tencentyun/cos-js-sdk-v5#76]
使用uploadFiles进行批量上传时，部分OPTIONS请求的URL与其他OPTIONS请求不一样，会带有`?uploads&prefix=`并且得到403的返回然后失败
![image](https://user-images.githubus`ercontent.com/7078156/78502808-86958600-7795-11ea-8adf-15b452e77bc8.png)
其他不带`?uploads&prefix=`的OPTIONS请求则会成功
![image](https://user-images.githubusercontent.com/7078156/78502842-b5abf780-7795-11ea-8ca6-efea58231b88.png)
失败比例在10-20%之间

**Comment by carsonxu** [comment]
uploadFiles 会根据文件大小用分片上传（cos.sliceUploadFile）和简单上传（cos.putObject）
需要提供给临时密钥足够的权限，Action 需要包含分片五个+PutObject。

**Comment by carsonxu** [comment]
// 简单上传
'name/cos:PutObject',
'name/cos:PostObject',
// 分片上传
'name/cos:InitiateMultipartUpload',
'name/cos:ListMultipartUploads',
'name/cos:ListParts',
'name/cos:UploadPart',
'name/cos:CompleteMultipartUpload',

**Comment by remote-star** [comment]
感谢
