### ISSUE TITLE
使用cos.uploadFiles批量上传时，有没有办法调用onTaskReady？

### ISSUE THREAD

**Issue by fakedestinyck** [tencentyun/cos-js-sdk-v5#78]
请问一下，我用的是js的前端上传。
文档中说`cos.uploadFiles`批量上传的时候会根据`SliceSize`判断是否要调用`sliceUploadFile`进行分块上传，请问这种情况下
- 有没有办法通过传入`onTaskReady`来获得`taskId`，从而实现断点续传呢？
- 如果用户中止上传（比如关闭浏览器），已经上传了的分块会占用存储空间吗？需要有类似于`multipartAbort`的调用来舍弃分块上传吗？

谢谢

**Comment by carsonxu** [comment]
1. 上传任务处理在 demo/queue/ 下有个完整的例子。
2. 如果页面没刷新过，上传失败了，可以调用 cos.restartTask(taskId); 重试单个任务
3. 两个途径可以获取 taskId，上传的 onTaskReady 回调里，cos.on('list-updated', fn); 事件里获取
4. 如果下次上传相同文件到相同 Key，分片上传是会自动续传的。浏览器这里有根据文件信息缓存了 UploadId。

**Comment by fakedestinyck** [comment]
@carsonxu 你好感谢回答！1、2和4都没什么问题，3的`cos.on('list-updated', fn)`也看到了也没有问题就是对于`onTaskReady`还是有一些疑惑，我在`cos.uploadFiles`中传入`onTaskReady 回调`，好像并没有任何用处:
```javascript
onTaskReady: function(taskId) {
	console.log(taskId); // 没有打印
},
onProgress: function(info) {
	var percent = parseInt(info.percent * 10000) / 100;
	var speed = parseInt((info.speed / 1024 / 1024) * 100) / 100;
},
```
这样写了之后，控制台并没有打印任何东西，我看官网的文档上写`uploadFiles`的参数里，并没有写`onTaskReady`,我不知道是不是我哪里理解错了
麻烦了

**Comment by carsonxu** [comment]
写错了换一个事件 list-update

**Comment by fakedestinyck** [comment]
好的谢谢 先close了
