### ISSUE TITLE
生成cos零时签名的 pathname和method，有什么用？

### ISSUE THREAD

**Issue by baoxiangyang** [tencentyun/cos-js-sdk-v5#8]
感觉没有什么用，但是method： ‘post’， pathname： ‘’ 或pathname： ‘/’.生成的签名才能上传到对象存储cos；其他的就会返回403

**Comment by carsonxu** [comment]
签名计算过程需要使用 method 和 pathname，如果签名里的计算参数和请求本身的 method 和 pathname 对应不上，就会返回 403。
签名计算参考：https://cloud.tencent.com/document/product/436/7778

**Comment by baoxiangyang** [comment]
@carsonxu 谢谢
