### ISSUE TITLE
有服务端重命名的示例么？

### ISSUE THREAD

**Issue by rxliuli** [tencentyun/cos-js-sdk-v5#83]
需求如下

前端上传一个文件，请求后端获取认证信息，返回的不仅是认证信息，同时还包含一个文件名（用以保证不重复），请问有这样的 demo 示例么？

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cos-js-sdk-v5/blob/master/demo/sts-put.html
可以用这个例子，改为选完文件后，找服务端获取可用文件名和上传凭证（Authorization 或 临时密钥），然后再上传。

**Comment by rxliuli** [comment]
> https://github.com/tencentyun/cos-js-sdk-v5/blob/master/demo/sts-put.html
> 可以用这个例子，改为选完文件后，找服务端获取可用文件名和上传凭证（Authorization 或 临时密钥），然后再上传。

只能这样么？不能像 v4 一样先获取 auth info，然后再（指定文件名信息）上传么？

**Comment by carsonxu** [comment]
v4 一个签名可以给不同文件名上传
v5 一个临时密钥如果限定的权限是目录权限，可以给不同文件名上传
v5一个签名只能给指定的文件名上传

这里：
1. 先取临时密钥、再指定文件名，这里两个步骤是分开的，感觉跟当前 v5 SDK 这样 先确定文件名、再取临时密钥是一样的。
2. 用上面这个例子你也可以先获取临时密钥(带目录权限)，再确定文件名，自行改写就好了。

**Comment by rxliuli** [comment]
> v4 一个签名可以给不同文件名上传
> v5 一个临时密钥如果限定的权限是目录权限，可以给不同文件名上传
> v5 一个签名只能给指定的文件名上传
> 
> 这里：
> 
> 1. 先取临时密钥、再指定文件名，这里两个步骤是分开的，感觉跟当前 v5 SDK 这样 先确定文件名、再取临时密钥是一样的。
> 2. 用上面这个例子你也可以先获取临时密钥 (带目录权限)，再确定文件名，自行改写就好了。

时序，关键是时序，文件名是由后端来生成的，我再调用获取临时密钥的接口之前无法拿到文件名，除非使用一个新的接口从后端获取文件名。。。

**Comment by carsonxu** [comment]
感觉你理解错我意思，这里选文件后，发一个请求到服务端，服务端先决定文件名、再获取对应临时密钥才返回给前端。
应该能满足你需要的，参考以下例子。

<details>
<summary>sts-put-server-name.html</summary>
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax Put 上传</title>
    <style>
        h1, h2 {
            font-weight: normal;
        }

        #msg {
            margin-top: 10px;
        }
    </style>
</head>
<body>

<h1>Ajax Put 上传</h1>

<input id="fileSelector" type="file">
<input id="submitBtn" type="submit">

<div id="msg"></div>

<script src="common/cos-auth.min.js"></script>
<script>
    (function () {
        // 请求用到的参数
        var Bucket = 'test-1250000000';
        var Region = 'ap-guangzhou';
        var protocol = location.protocol === 'https:' ? 'https:' : 'http:';
        var prefix = protocol + '//' + Bucket + '.cos.' + Region + '.myqcloud.com/';

        // 对更多字符编码的 url encode 格式
        var camSafeUrlEncode = function (str) {
            return encodeURIComponent(str)
                .replace(/!/g, '%21')
                .replace(/'/g, '%27')
                .replace(/\(/g, '%28')
                .replace(/\)/g, '%29')
                .replace(/\*/g, '%2A');
        };

        // 计算签名
        var getAuthAndKey = function (options, callback) {
            var url = '../server/getStsAndKey.php?filename=' + encodeURIComponent(options.FileName); // 这里用一个接口获取临时密钥和文件名
            var xhr = new XMLHttpRequest();
            xhr.open('GET', url, true);
            xhr.onload = function (e) {
                var result, credentials;
                try {
                    result = (new Function('return ' + xhr.responseText))();
                    credentials = result.credentials;
                } catch (e) {}
                if (result && credentials) {
                    callback(null, {
                        Key: result.Key, // 这里在后端加一个字段决定上传的文件名
                        XCosSecurityToken: credentials.sessionToken,
                        Authorization: CosAuth({
                            SecretId: credentials.tmpSecretId,
                            SecretKey: credentials.tmpSecretKey,
                            Method: options.Method,
                            Pathname: options.Pathname,
                        }),
                    });
                } else {
                    console.error(xhr.responseText);
                    callback('获取签名出错');
                }
            };
            xhr.onerror = function (e) {
                callback('获取签名出错');
            };
            xhr.send();
        };

        // 上传文件
        var uploadFile = function (file, callback) {
            getAuthAndKey({Method: 'PUT', FileName: file.name}, function (err, info) {
                var Key = info.key;

                if (err) {
                    alert(err);
                    return;
                }

                var auth = info.Authorization;
                var XCosSecurityToken = info.XCosSecurityToken;
                var url = prefix + camSafeUrlEncode(Key).replace(/%2F/g, '/');
                var xhr = new XMLHttpRequest();
                xhr.open('PUT', url, true);
                xhr.setRequestHeader('Authorization', auth);
                XCosSecurityToken && xhr.setRequestHeader('x-cos-security-token', XCosSecurityToken);
                xhr.upload.onprogress = function (e) {
                    console.log('上传进度 ' + (Math.round(e.loaded / e.total * 10000) / 100) + '%');
                };
                xhr.onload = function () {
                    if (xhr.status === 200 || xhr.status === 206) {
                        var ETag = xhr.getResponseHeader('etag');
                        callback(null, {url: url, ETag: ETag});
                    } else {
                        callback('文件 ' + Key + ' 上传失败，状态码：' + xhr.status);
                    }
                };
                xhr.onerror = function () {
                    callback('文件 ' + Key + ' 上传失败，请检查是否没配置 CORS 跨域规则');
                };
                xhr.send(file);
            });
        };

        // 监听表单提交
        document.getElementById('submitBtn').onclick = function (e) {
            var file = document.getElementById('fileSelector').files[0];
            if (!file) {
                document.getElementById('msg').innerText = '未选择上传文件';
                return;
            }
            file && uploadFile(file, function (err, data) {
                console.log(err || data);
                document.getElementById('msg').innerText = err ? err : ('上传成功，ETag=' + data.ETag);
            });
        };
    })();
</script>

</body>
</html>
```
</details>

**Comment by rxliuli** [comment]
> <script src="common/cos-auth.min.js"></script> <script> (function () { // 请求用到的参数 var Bucket = 'test-1250000000'; var Region = 'ap-guangzhou'; var protocol = location.protocol === 'https:' ? 'https:' : 'http:'; var prefix = protocol + '//' + Bucket + '.cos.' + Region + '.myqcloud.com/'; // 对更多字符编码的 url encode 格式 var camSafeUrlEncode = function (str) { return encodeURIComponent (str) .replace (/!/g, '%21') .replace (/'/g, '%27') .replace (/\(/g, '%28') .replace (/\)/g, '%29') .replace (/\*/g, '%2A'); }; // 计算签名 var getAuthAndKey = function (options, callback) { var url = '../server/getStsAndKey.php?filename=' + encodeURIComponent (options.FileName); // 这里用一个接口获取临时密钥和文件名 var xhr = new XMLHttpRequest (); xhr.open ('GET', url, true); xhr.onload = function (e) { var result, credentials; try { result = (new Function ('return ' + xhr.responseText))(); credentials = result.credentials; } catch (e) {} if (result && credentials) { callback (null, { Key: result.Key, // 这里在后端加一个字段决定上传的文件名 XCosSecurityToken: credentials.sessionToken, Authorization: CosAuth ({ SecretId: credentials.tmpSecretId, SecretKey: credentials.tmpSecretKey, Method: options.Method, Pathname: options.Pathname, }), }); } else { console.error (xhr.responseText); callback (' 获取签名出错 '); } }; xhr.onerror = function (e) { callback (' 获取签名出错 '); }; xhr.send (); }; // 上传文件 var uploadFile = function (file, callback) { getAuthAndKey ({Method: 'PUT', FileName: file.name}, function (err, info) { var Key = info.key; if (err) { alert (err); return; } var auth = info.Authorization; var XCosSecurityToken = info.XCosSecurityToken; var url = prefix + camSafeUrlEncode (Key).replace (/%2F/g, '/'); var xhr = new XMLHttpRequest (); xhr.open ('PUT', url, true); xhr.setRequestHeader ('Authorization', auth); XCosSecurityToken && xhr.setRequestHeader ('x-cos-security-token', XCosSecurityToken); xhr.upload.onprogress = function (e) { console.log (' 上传进度 ' + (Math.round (e.loaded/e.total * 10000) / 100) + '%'); }; xhr.onload = function () { if (xhr.status === 200 || xhr.status === 206) { var ETag = xhr.getResponseHeader ('etag'); callback (null, {url: url, ETag: ETag}); } else { callback (' 文件 ' + Key + ' 上传失败，状态码：' + xhr.status); } }; xhr.onerror = function () { callback (' 文件 ' + Key + ' 上传失败，请检查是否没配置 CORS 跨域规则 '); }; xhr.send (file); }); }; // 监听表单提交 document.getElementById ('submitBtn').onclick = function (e) { var file = document.getElementById ('fileSelector').files [0]; if (!file) { document.getElementById ('msg').innerText = ' 未选择上传文件 '; return; } file && uploadFile (file, function (err, data) { console.log (err || data); document.getElementById ('msg').innerText = err ? err : (' 上传成功，ETag=' + data.ETag); }); }; })(); </script>

可否把代码格式化一下，全变成注释了。。。

**Comment by carsonxu** [comment]
已改

**Comment by rxliuli** [comment]
> 已改

可以实现了，但 sdk 看来是没什么用处了

**Comment by carsonxu** [comment]
分片上传会比较复杂，还有很多别的接口，可以用 SDK。

**Comment by rxliuli** [comment]
sdk 无法解决这个问题，你上面的示例也只用了 cos auth 模块而已

**Comment by carsonxu** [comment]
是的，SDK 后面有考虑支持这种后端决定文件名的场景。

**Comment by rxliuli** [comment]
我觉得先把类型定义加上更好，腾讯的 sdk 很少有照顾开发者体验的，包括但不限于 cos、vod、tim。。。各种乱七八糟的云服务 sdk，都是难以直视的坑，就拿 v5 来说，示例用 xhr，返回用 xml。。。感觉就像是另一些世界的人写的东西

**Comment by carsonxu** [comment]
嗯，我们陆续优化体验问题。

**Comment by rxliuli** [comment]
关键是改善这点并不难，我一个人就能写好公司 npm 私服的[工具](https://github.com/rxliuli/liuli-cli)，实在难以理解以腾讯的体量会无法做的更好

**Comment by rxliuli** [comment]
cos-auth 有单独的 npm 包么？我找到一个 qcloud-cos-auth，但已经是 3 年前的了，我不确定这是否能用或是是否为官方的

https://www.npmjs.com/package/qcloud-cos-auth

**Comment by rxliuli** [comment]
测试了一下上面的示例，出现了 403

cos-auth 的问题使用 `getAuthorization` 方法代替了

```js
fetch('http://test-1253492636.cos.ap-guangzhou.myqcloud.com//rs/rvImg/20200629/hJaFXk2qMPdgHbOf.png', {
  credentials: 'include',
  headers: {
    accept: '*/*',
    'accept-language': 'zh-CN',
    authorization:
      'q-sign-algorithm=sha1&q-ak=AKIDx0YyiEfIiMsMfo_SxDASnsYTfYY_Bcpd7fZt1Yw8CRTqDRxbQqiUbQ4QrfvkeyMd&q-sign-time=1593414926;1593415826&q-key-time=1593414926;1593415826&q-header-list=&q-url-param-list=&q-signature=56cf16e3b95826ce7ce53f9f1c8eadb42ed328bb',
    'content-type': 'image/png',
    'proxy-connection': 'keep-alive',
    'x-cos-security-token':
      'Wm1PzE39iiFtZnU70TWnDsQ34QUypOua6761880ac2f7e862a6561ecf6ffc7225ToGv0Gj6XS-7Jl70xRSwT0l3taQ1YcipsDyXS80SlQ35cLHMYdno4UxXX_Qxx8uwsloFd7sCfXoUDP-OrLk__MQg44lVBiY53DN9oPQrP2jlk2nrTQzrmV8N4dGMgUBVbAvm-AfI42t0m8wAJahl2-l2icALDPNOdbURnpGxdLiObcQuzA4p2_EiPPyi9c0u0AfEyt5EHlkacYoNgWMTnARwcJyi8C7AqXAD_lQ528Y',
  },
  referrer: 'http://localhost:5000/',
  referrerPolicy: 'no-referrer-when-downgrade',
  body: null,
  method: 'PUT',
  mode: 'cors',
})

```

**Comment by rxliuli** [comment]
测试了一下上面的示例，出现了 403

cos-auth 的问题使用 `getAuthorization` 方法代替了

```js
fetch('http://test-1253492636.cos.ap-guangzhou.myqcloud.com//rs/rvImg/20200629/hJaFXk2qMPdgHbOf.png', {
  credentials: 'include',
  headers: {
    accept: '*/*',
    'accept-language': 'zh-CN',
    authorization:
      'q-sign-algorithm=sha1&q-ak=AKIDx0YyiEfIiMsMfo_SxDASnsYTfYY_Bcpd7fZt1Yw8CRTqDRxbQqiUbQ4QrfvkeyMd&q-sign-time=1593414926;1593415826&q-key-time=1593414926;1593415826&q-header-list=&q-url-param-list=&q-signature=56cf16e3b95826ce7ce53f9f1c8eadb42ed328bb',
    'content-type': 'image/png',
    'proxy-connection': 'keep-alive',
    'x-cos-security-token':
      'Wm1PzE39iiFtZnU70TWnDsQ34QUypOua6761880ac2f7e862a6561ecf6ffc7225ToGv0Gj6XS-7Jl70xRSwT0l3taQ1YcipsDyXS80SlQ35cLHMYdno4UxXX_Qxx8uwsloFd7sCfXoUDP-OrLk__MQg44lVBiY53DN9oPQrP2jlk2nrTQzrmV8N4dGMgUBVbAvm-AfI42t0m8wAJahl2-l2icALDPNOdbURnpGxdLiObcQuzA4p2_EiPPyi9c0u0AfEyt5EHlkacYoNgWMTnARwcJyi8C7AqXAD_lQ528Y',
  },
  referrer: 'http://localhost:5000/',
  referrerPolicy: 'no-referrer-when-downgrade',
  body: null,
  method: 'PUT',
  mode: 'cors',
})

```

**Comment by rxliuli** [comment]
> 测试了一下上面的示例，出现了 403
> 
> 文件 /rs/rvImg/20200629/hJaFXk2qMPdgHbOf.png 上传失败，状态码：403
> 
> HTTP/1.1 403 Forbidden
> Content-Type: application/xml
> Content-Length: 696
> Connection: close
> Access-Control-Allow-Methods: PUT,GET,POST,HEAD
> Access-Control-Allow-Origin: *
> Access-Control-Max-Age: 60
> Date: Mon, 29 Jun 2020 07:15:29 GMT
> Server: tencent-cos
> x-cos-request-id: NWVmOTk1MTFfZjZhMDNiMGFfOGJkY18xNDFkMTJl
> x-cos-trace-id: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjYjdkMDE0YzdiNDU3MThiMzQ3NzBkMmQwZjE1ZWVlZmU=
> Proxy-Connection: keep-alive
> 
> cos-auth 的问题使用 `getAuthorization` 方法代替了
> 
> ```js
> fetch('http://test-1253492636.cos.ap-guangzhou.myqcloud.com//rs/rvImg/20200629/hJaFXk2qMPdgHbOf.png', {
>   credentials: 'include',
>   headers: {
>     accept: '*/*',
>     'accept-language': 'zh-CN',
>     authorization:
>       'q-sign-algorithm=sha1&q-ak=AKIDx0YyiEfIiMsMfo_SxDASnsYTfYY_Bcpd7fZt1Yw8CRTqDRxbQqiUbQ4QrfvkeyMd&q-sign-time=1593414926;1593415826&q-key-time=1593414926;1593415826&q-header-list=&q-url-param-list=&q-signature=56cf16e3b95826ce7ce53f9f1c8eadb42ed328bb',
>     'content-type': 'image/png',
>     'proxy-connection': 'keep-alive',
>     'x-cos-security-token':
>       'Wm1PzE39iiFtZnU70TWnDsQ34QUypOua6761880ac2f7e862a6561ecf6ffc7225ToGv0Gj6XS-7Jl70xRSwT0l3taQ1YcipsDyXS80SlQ35cLHMYdno4UxXX_Qxx8uwsloFd7sCfXoUDP-OrLk__MQg44lVBiY53DN9oPQrP2jlk2nrTQzrmV8N4dGMgUBVbAvm-AfI42t0m8wAJahl2-l2icALDPNOdbURnpGxdLiObcQuzA4p2_EiPPyi9c0u0AfEyt5EHlkacYoNgWMTnARwcJyi8C7AqXAD_lQ528Y',
>   },
>   referrer: 'http://localhost:5000/',
>   referrerPolicy: 'no-referrer-when-downgrade',
>   body: null,
>   method: 'PUT',
>   mode: 'cors',
> })
> ```

具体错误 xml 返回是


403 Forbidden | SignatureDoesNotMatch | 客户端计算的签名与 COS 服务端计算的签名不一致

所以说 COS.getAuthorization 和 CosAuth 的定义不一样么？

**Comment by carsonxu** [comment]
一致的，CosAuth 只是单独拿出来一个 js。
这里可能是你签名的 pathname 是 /rs/rvImg/20200629/hJaFXk2qMPdgHbOf.png
发请求缺多了一个斜杠：//rs/rvImg/20200629/hJaFXk2qMPdgHbOf.png

**Comment by rxliuli** [comment]
跨域是什么鬼？我确定 cos 设置了允许所有 origin（*），但还是出现了跨域错误

Access to XMLHttpRequest at 'http://test-1253492636.cos.ap-guangzhou.myqcloud.com/rs/rvImg/20200629/0JLvJhb9k6P1AXDp.png' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
PUT http://test-1253492636.cos.ap-guangzhou.myqcloud.com/rs/rvImg/20200629/0JLvJhb9k6P1AXDp.png net::ERR_FAILED
文件 /rs/rvImg/20200629/0JLvJhb9k6P1AXDp.png 上传失败，请检查是否没配置 CORS 跨域规则

Invoke-WebRequest -Uri "http://test-1253492636.cos.ap-guangzhou.myqcloud.com/rs/rvImg/20200629/0JLvJhb9k6P1AXDp.png" `
-Method "PUT" `
-Headers @{
"User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
  "Referer"="http://localhost:3000/"
  "DNT"="1"
  "x-cos-security-token"="QZgiFHHtXqyvtPeWy7taWZ23aoPdOqny81e13d04b1acd67251b848c3b9982885W6i5Xp6yglAAqkHtyTG4zxbgWJMTv10AtEmemKgkgzgCpBjpCUTuwCpIpDG9BZXGgQTRvjiqcIke8yG2DVBwTf1I8CN3GlcLA0T8uOrQh_0ZHumGZTgzoOPVREoWl-CuEDQzm0yiL91sE1KYZj9hbTdGzjuCB52JdslkyiiOP80RivsojubW_eXJ1O2Z2iJxPJmg00XBAi-rmMhKpZ50WzmWfiynjGRFEMnKErLmrF4"
  "Authorization"="q-sign-algorithm=sha1&q-ak=AKIDWhJKFDVTOgysH4cL7iYscYLOL7HTIX3JfJurUtOzZ7CZUfv6HkLPvfWneMWaHzx9&q-sign-time=1593424233;1593425133&q-key-time=1593424233;1593425133&q-header-list=&q-url-param-list=&q-signature=8b212a785bd6afd4ad8686481c2812a2e639bb35"
} `
-ContentType "image/png"

**Comment by carsonxu** [comment]
AllowHeaders 也要配置 *
Expose-Headers 要加 ETag

**Comment by rxliuli** [comment]
> AllowHeaders 也要配置 *
> Expose-Headers 要加 ETag

我加了，但似乎没有意义

![image](https://user-images.githubusercontent.com/24560368/85999506-c55a7580-ba3e-11ea-883c-580049f00bb4.png)

**Comment by carsonxu** [comment]
在你最后截图这个界面，配置：
Allow-Headers 为 *

**Comment by rxliuli** [comment]
> 在你最后截图这个界面，配置：
> Allow-Headers 为 *

我试一下
