### ISSUE TITLE
nextjs打包不成功navigator is not defined

### ISSUE THREAD

**Issue by impfans** [tencentyun/cos-js-sdk-v5#84]
如题打包会出现报错 其他文件里所有操作js的都会报not defined

**Comment by carsonxu** [comment]
不支持服务端渲染，可以改为 script 标签加载。

**Comment by impfans** [comment]
改为script后加载不到js里的东西啊。

**Comment by impfans** [comment]
> 不支持服务端渲染，可以更改脚本标签加载。

更改脚本后加载不到js里的东西啊。

**Comment by impfans** [comment]
> 不支持服务端渲染，可以改为 script 标签加载。

我把这个文件关闭了ssr，界面不报错了，但是打包的时候还是会报错。。

**Comment by carsonxu** [comment]
尝试过 ssr: false 也是有很多问题，这样可以解决问题：
在 next.config.js 里指定在页面头部用 script 标签引入 cos sdk
```javascript
module.exports = {
    head: {
        script: [
            {src: 'https://example.com/static/lib/cos-js-sdk-v5.min.js'}
        ]
    }
}
```
