### ISSUE TITLE
The error is not complete

### ISSUE THREAD

**Issue by nanaSun** [tencentyun/cos-js-sdk-v5#85]
https://github.com/tencentyun/cos-js-sdk-v5/blob/de1705921d5ca8c2e468f0ab83b360ff7e731727/dist/cos-js-sdk-v5.js#L10177

I see there is a lot of error code on the [sdk doc](https://cloud.tencent.com/document/product/436/7730), but here jssdk error is limited. 
And cos has no record about failure upload, so we need to record each error record.
But Cos jssdk only return `{ error: 'error', headers: {} }`, It's meaningless.
So I hope Cos jssdk could return detailed error message to us.

**Comment by carsonxu** [comment]
CORS error caused by  CORS error or some unknow network error, and JS cannot get statusCode and headers.
We will fix it in a later version.

**Comment by carsonxu** [comment]
We optimized the tips:
{error: 'CORS blocked or network error'}
