### ISSUE TITLE
小程序上传图片成功，但是有错误提示

### ISSUE THREAD

**Issue by nevertback** [tencentyun/cos-js-sdk-v5#87]
错误提示：
[xmldom error]	invalid doc source 
@#[line:0,col:undefined]
![未命名1598516230](https://user-images.githubusercontent.com/4335773/91415656-f27da580-e880-11ea-83f2-b3ecadabf01c.png)

**Comment by carsonxu** [comment]
小程序用这个 cos-wx-sdk-v5  https://cloud.tencent.com/document/product/436/31953

**Comment by nevertback** [comment]
> 小程序用这个 cos-wx-sdk-v5 https://cloud.tencent.com/document/product/436/31953

提错地方了。。我去那个里面提了，不好意思
