### ISSUE TITLE
 import * as COS from "cos-js-sdk-v5" 导出 报错

### ISSUE THREAD

**Issue by NatsumeF** [tencentyun/cos-js-sdk-v5#98]
https://github.com/tencentyun/cos-js-sdk-v5/blob/64d78772961a7c6008e3ec311eba1ef78af8ad01/src/util.js#L489

这里使用了一个global的全局对象

导致了 Error: Uncaught (in promise): ReferenceError: global is not defined

建议使用es6的 globalThis

**Comment by carsonxu** [comment]
fixed
